// <auto-generated />
using System;
using System.Collections.Generic;
using Firebase_Auth.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace firebase_auth.Migrations
{
    [DbContext(typeof(CoreDbContext))]
    [Migration("20250513023441_AddNotificationTopicAndItsSeeder")]
    partial class AddNotificationTopicAndItsSeeder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Firebase_Auth.Data.Entities.Authentication.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Code = "CreateContent",
                            Description = "Permission to create content",
                            Name = "CreateContent",
                            State = 4
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Code = "EditContent",
                            Description = "Permission to edit content",
                            Name = "EditContent",
                            State = 4
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Code = "DeleteContent",
                            Description = "Permission to delete content",
                            Name = "DeleteContent",
                            State = 4
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Code = "ViewContent",
                            Description = "Permission to view content",
                            Name = "ViewContent",
                            State = 4
                        });
                });

            modelBuilder.Entity("Firebase_Auth.Data.Entities.Authentication.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Administrator role with full permissions",
                            Name = "admin",
                            State = 4
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Description = "Editor role with editing permissions",
                            Name = "moderator",
                            State = 4
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Description = "User role with viewing permissions",
                            Name = "user",
                            State = 4
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            Description = "Root",
                            Name = "root",
                            State = 4
                        });
                });

            modelBuilder.Entity("Firebase_Auth.Data.Entities.Authentication.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("99999999-9999-9999-9999-999999999999"),
                            PermissionId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            RoleId = new Guid("99999999-9999-9999-9999-999999999999"),
                            PermissionId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            RoleId = new Guid("99999999-9999-9999-9999-999999999999"),
                            PermissionId = new Guid("66666666-6666-6666-6666-666666666666")
                        },
                        new
                        {
                            RoleId = new Guid("99999999-9999-9999-9999-999999999999"),
                            PermissionId = new Guid("77777777-7777-7777-7777-777777777777")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("66666666-6666-6666-6666-666666666666")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("77777777-7777-7777-7777-777777777777")
                        },
                        new
                        {
                            RoleId = new Guid("22222222-2222-2222-2222-222222222222"),
                            PermissionId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            RoleId = new Guid("22222222-2222-2222-2222-222222222222"),
                            PermissionId = new Guid("77777777-7777-7777-7777-777777777777")
                        },
                        new
                        {
                            RoleId = new Guid("33333333-3333-3333-3333-333333333333"),
                            PermissionId = new Guid("77777777-7777-7777-7777-777777777777")
                        });
                });

            modelBuilder.Entity("Firebase_Auth.Data.Entities.Authentication.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdditionalData")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeviceToken")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FirebaseUid")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("FullName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<bool>("RequirePasswordReset")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("FirebaseUid")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Firebase_Auth.Data.Entities.Common.Notification.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Destination")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NotificationRecipient")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PushOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Firebase_Auth.Data.Entities.Common.Notification.NotificationTopic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<string>("TopicName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d48c2c02-3d5c-49dd-b8cb-ec55df1c9dc3"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedOn = new DateTime(2025, 5, 13, 2, 34, 40, 211, DateTimeKind.Utc).AddTicks(1511),
                            Description = "General notifications for all users",
                            State = 4,
                            TopicName = "general-notification"
                        },
                        new
                        {
                            Id = new Guid("a2dd7ba9-8682-4860-b5c3-acf8cc600ff3"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedOn = new DateTime(2025, 5, 13, 2, 34, 40, 211, DateTimeKind.Utc).AddTicks(1872),
                            Description = "Latest sports news and updates",
                            State = 4,
                            TopicName = "sports-news"
                        },
                        new
                        {
                            Id = new Guid("83a0c9a1-168b-490b-8175-53acdf84fc0d"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedOn = new DateTime(2025, 5, 13, 2, 34, 40, 211, DateTimeKind.Utc).AddTicks(1877),
                            Description = "Weather alerts and updates",
                            State = 4,
                            TopicName = "weather-updates"
                        },
                        new
                        {
                            Id = new Guid("31a475e9-4c99-40c8-ae61-a04a85167fa3"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedOn = new DateTime(2025, 5, 13, 2, 34, 40, 211, DateTimeKind.Utc).AddTicks(1878),
                            Description = "Special offers and marketing promotions",
                            State = 4,
                            TopicName = "marketing-promo"
                        });
                });

            modelBuilder.Entity("Firebase_Auth.Data.Entities.Movies.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<string>>("Cast")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Directors")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Language")
                        .HasColumnType("text");

                    b.Property<string>("PosterUrl")
                        .HasColumnType("text");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TrailerUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8f73cbb6-a1c5-44f8-96f1-808fc4a7786d"),
                            Cast = new List<string> { "ipsa", "autem", "et" },
                            Country = "Bulgaria",
                            CreatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 198, DateTimeKind.Utc).AddTicks(4784),
                            CreatedBy = "",
                            Description = "Voluptas exercitationem est laudantium nihil ut laboriosam nostrum.",
                            Directors = new List<string> { "maxime", "omnis" },
                            DurationMinutes = 100,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=531",
                            Rating = 6.7204488679518528,
                            ReleaseDate = new DateTime(2020, 5, 24, 17, 16, 59, 884, DateTimeKind.Local).AddTicks(2154),
                            State = 4,
                            Title = "Fantastic Granite Pants",
                            TrailerUrl = "https://marietta.com",
                            UpdatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 198, DateTimeKind.Utc).AddTicks(4792)
                        },
                        new
                        {
                            Id = new Guid("98cbec81-778e-4410-a27d-018dfa568c27"),
                            Cast = new List<string> { "earum", "qui", "et" },
                            Country = "Panama",
                            CreatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 208, DateTimeKind.Utc).AddTicks(4800),
                            CreatedBy = "",
                            Description = "Quaerat nulla provident molestiae voluptatum cumque ut id.",
                            Directors = new List<string> { "sapiente" },
                            DurationMinutes = 147,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=315",
                            Rating = 1.0242544174242014,
                            ReleaseDate = new DateTime(2025, 2, 17, 11, 18, 42, 281, DateTimeKind.Local).AddTicks(158),
                            State = 4,
                            Title = "Refined Steel Chair",
                            TrailerUrl = "http://margaret.org",
                            UpdatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 208, DateTimeKind.Utc).AddTicks(4806)
                        },
                        new
                        {
                            Id = new Guid("e605d572-cd2d-4eef-80a3-3a46ba194159"),
                            Cast = new List<string> { "voluptas", "et", "eveniet" },
                            Country = "Svalbard & Jan Mayen Islands",
                            CreatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 208, DateTimeKind.Utc).AddTicks(5881),
                            CreatedBy = "",
                            Description = "Omnis enim inventore dolor et vel explicabo commodi.",
                            Directors = new List<string> { "corrupti" },
                            DurationMinutes = 162,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=830",
                            Rating = 4.3062247386632908,
                            ReleaseDate = new DateTime(2015, 12, 19, 20, 39, 57, 761, DateTimeKind.Local).AddTicks(9683),
                            State = 4,
                            Title = "Unbranded Rubber Tuna",
                            TrailerUrl = "https://sydney.org",
                            UpdatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 208, DateTimeKind.Utc).AddTicks(5882)
                        },
                        new
                        {
                            Id = new Guid("56f7839a-3e69-4468-be58-3d3a9ac65f63"),
                            Cast = new List<string> { "dolorum", "et", "at", "ipsum", "sed" },
                            Country = "Kenya",
                            CreatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 208, DateTimeKind.Utc).AddTicks(6011),
                            CreatedBy = "",
                            Description = "Ex error error magni enim amet dolorem sit eos.",
                            Directors = new List<string> { "non", "aut" },
                            DurationMinutes = 97,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=1069",
                            Rating = 8.9824636134350619,
                            ReleaseDate = new DateTime(2020, 8, 29, 3, 33, 9, 429, DateTimeKind.Local).AddTicks(5063),
                            State = 4,
                            Title = "Refined Fresh Soap",
                            TrailerUrl = "https://ashtyn.org",
                            UpdatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 208, DateTimeKind.Utc).AddTicks(6011)
                        },
                        new
                        {
                            Id = new Guid("a3cb626f-7c0f-448d-8261-53d2e2fb35ca"),
                            Cast = new List<string> { "et", "eum", "sed", "velit" },
                            Country = "Cambodia",
                            CreatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 208, DateTimeKind.Utc).AddTicks(6224),
                            CreatedBy = "",
                            Description = "Sint sapiente quidem veniam totam ullam iure dolores.",
                            Directors = new List<string> { "iusto" },
                            DurationMinutes = 89,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=668",
                            Rating = 8.7991318948198192,
                            ReleaseDate = new DateTime(2017, 3, 28, 10, 30, 15, 918, DateTimeKind.Local).AddTicks(3714),
                            State = 4,
                            Title = "Licensed Metal Mouse",
                            TrailerUrl = "http://anne.org",
                            UpdatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 208, DateTimeKind.Utc).AddTicks(6224)
                        },
                        new
                        {
                            Id = new Guid("003687b4-1b7a-4686-a8d7-5ed6aa2b3d54"),
                            Cast = new List<string> { "nam", "nisi", "ipsam", "laborum", "consectetur", "laborum", "incidunt" },
                            Country = "Vietnam",
                            CreatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 208, DateTimeKind.Utc).AddTicks(6326),
                            CreatedBy = "",
                            Description = "Necessitatibus eveniet odit repudiandae illo.",
                            Directors = new List<string> { "exercitationem", "officia", "est" },
                            DurationMinutes = 158,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=506",
                            Rating = 8.0153903375699542,
                            ReleaseDate = new DateTime(2018, 9, 26, 9, 10, 57, 779, DateTimeKind.Local).AddTicks(9537),
                            State = 4,
                            Title = "Incredible Wooden Car",
                            TrailerUrl = "https://barry.org",
                            UpdatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 208, DateTimeKind.Utc).AddTicks(6326)
                        },
                        new
                        {
                            Id = new Guid("ce0eadb9-2fc9-4791-96fc-e5fe2aae96be"),
                            Cast = new List<string> { "amet", "officiis", "odit", "accusamus", "unde", "dolor" },
                            Country = "American Samoa",
                            CreatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 208, DateTimeKind.Utc).AddTicks(6470),
                            CreatedBy = "",
                            Description = "Harum omnis vel qui odit earum.",
                            Directors = new List<string> { "pariatur" },
                            DurationMinutes = 173,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=842",
                            Rating = 1.3306473481819396,
                            ReleaseDate = new DateTime(2019, 10, 25, 2, 30, 8, 303, DateTimeKind.Local).AddTicks(53),
                            State = 4,
                            Title = "Ergonomic Granite Pizza",
                            TrailerUrl = "https://layla.info",
                            UpdatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 208, DateTimeKind.Utc).AddTicks(6471)
                        },
                        new
                        {
                            Id = new Guid("ed23e911-6b9e-41df-84fb-713595684560"),
                            Cast = new List<string> { "cum", "recusandae", "qui", "soluta", "similique" },
                            Country = "United Arab Emirates",
                            CreatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 208, DateTimeKind.Utc).AddTicks(6568),
                            CreatedBy = "",
                            Description = "Quo totam sit aspernatur eum exercitationem deserunt eos ipsum.",
                            Directors = new List<string> { "porro", "id", "odit" },
                            DurationMinutes = 85,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=493",
                            Rating = 6.4375490869883469,
                            ReleaseDate = new DateTime(2018, 10, 12, 23, 14, 16, 220, DateTimeKind.Local).AddTicks(8784),
                            State = 4,
                            Title = "Awesome Concrete Pizza",
                            TrailerUrl = "https://chasity.org",
                            UpdatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 208, DateTimeKind.Utc).AddTicks(6569)
                        },
                        new
                        {
                            Id = new Guid("44067f37-ad2b-4ba6-b298-36a7b39c7e11"),
                            Cast = new List<string> { "magnam", "labore", "eius", "facere" },
                            Country = "Holy See (Vatican City State)",
                            CreatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 208, DateTimeKind.Utc).AddTicks(6677),
                            CreatedBy = "",
                            Description = "Ut veritatis voluptates aliquid.",
                            Directors = new List<string> { "et", "quia" },
                            DurationMinutes = 85,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=421",
                            Rating = 2.6752767770731882,
                            ReleaseDate = new DateTime(2019, 6, 12, 4, 45, 30, 572, DateTimeKind.Local).AddTicks(6012),
                            State = 4,
                            Title = "Gorgeous Frozen Keyboard",
                            TrailerUrl = "http://jordi.name",
                            UpdatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 208, DateTimeKind.Utc).AddTicks(6677)
                        },
                        new
                        {
                            Id = new Guid("2951079c-5b59-438f-a61f-9e8e93526920"),
                            Cast = new List<string> { "commodi", "quidem", "error", "repellat", "molestiae" },
                            Country = "Serbia",
                            CreatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 208, DateTimeKind.Utc).AddTicks(6815),
                            CreatedBy = "",
                            Description = "Autem officiis at quo.",
                            Directors = new List<string> { "qui", "et" },
                            DurationMinutes = 127,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=297",
                            Rating = 4.5181305577518192,
                            ReleaseDate = new DateTime(2018, 6, 20, 10, 30, 18, 320, DateTimeKind.Local).AddTicks(1196),
                            State = 4,
                            Title = "Small Metal Cheese",
                            TrailerUrl = "http://adell.name",
                            UpdatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 208, DateTimeKind.Utc).AddTicks(6816)
                        },
                        new
                        {
                            Id = new Guid("1e540378-a27e-4cdb-92db-397661672ea2"),
                            Cast = new List<string> { "mollitia", "quaerat", "dolorem", "quibusdam", "laboriosam", "reprehenderit", "consequatur" },
                            Country = "Malawi",
                            CreatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 208, DateTimeKind.Utc).AddTicks(6903),
                            CreatedBy = "",
                            Description = "Itaque excepturi quasi non dolor velit.",
                            Directors = new List<string> { "qui", "facilis" },
                            DurationMinutes = 112,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=486",
                            Rating = 9.8139697255574241,
                            ReleaseDate = new DateTime(2024, 10, 7, 1, 3, 42, 512, DateTimeKind.Local).AddTicks(7682),
                            State = 4,
                            Title = "Unbranded Rubber Mouse",
                            TrailerUrl = "https://herminia.biz",
                            UpdatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 208, DateTimeKind.Utc).AddTicks(6903)
                        },
                        new
                        {
                            Id = new Guid("ea3d3431-f11a-43fa-803a-ee54191b9803"),
                            Cast = new List<string> { "dicta", "dolor", "totam", "error", "quia", "molestias" },
                            Country = "Uzbekistan",
                            CreatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 208, DateTimeKind.Utc).AddTicks(7038),
                            CreatedBy = "",
                            Description = "Dolore neque corrupti voluptas.",
                            Directors = new List<string> { "porro", "est", "et" },
                            DurationMinutes = 173,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=786",
                            Rating = 9.1771051841045228,
                            ReleaseDate = new DateTime(2018, 3, 14, 23, 2, 19, 325, DateTimeKind.Local).AddTicks(6471),
                            State = 4,
                            Title = "Awesome Cotton Bacon",
                            TrailerUrl = "https://marion.com",
                            UpdatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 208, DateTimeKind.Utc).AddTicks(7038)
                        },
                        new
                        {
                            Id = new Guid("157381d2-6827-4e70-baab-9c5a377441d5"),
                            Cast = new List<string> { "reiciendis", "iure", "doloribus", "quae", "ut", "amet" },
                            Country = "Trinidad and Tobago",
                            CreatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 208, DateTimeKind.Utc).AddTicks(7132),
                            CreatedBy = "",
                            Description = "Cumque et aut non rerum molestiae doloribus non veniam cum.",
                            Directors = new List<string> { "natus", "magni" },
                            DurationMinutes = 113,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=917",
                            Rating = 4.8126089041828735,
                            ReleaseDate = new DateTime(2017, 8, 13, 21, 1, 31, 475, DateTimeKind.Local).AddTicks(8773),
                            State = 4,
                            Title = "Incredible Granite Keyboard",
                            TrailerUrl = "http://tiffany.name",
                            UpdatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 208, DateTimeKind.Utc).AddTicks(7132)
                        },
                        new
                        {
                            Id = new Guid("80a01912-9b09-4e47-8d26-0feac2831746"),
                            Cast = new List<string> { "pariatur", "est", "et" },
                            Country = "Saint Barthelemy",
                            CreatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 208, DateTimeKind.Utc).AddTicks(7239),
                            CreatedBy = "",
                            Description = "Nam eum optio sequi ut.",
                            Directors = new List<string> { "perspiciatis", "delectus", "quibusdam" },
                            DurationMinutes = 121,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=1083",
                            Rating = 4.0341399802985585,
                            ReleaseDate = new DateTime(2019, 11, 14, 3, 30, 27, 840, DateTimeKind.Local).AddTicks(4552),
                            State = 4,
                            Title = "Ergonomic Fresh Shirt",
                            TrailerUrl = "https://lexie.biz",
                            UpdatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 208, DateTimeKind.Utc).AddTicks(7239)
                        },
                        new
                        {
                            Id = new Guid("ea2d8944-c15f-48cd-8978-95d9445fafef"),
                            Cast = new List<string> { "nemo", "cum", "excepturi", "molestiae" },
                            Country = "Djibouti",
                            CreatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 208, DateTimeKind.Utc).AddTicks(7399),
                            CreatedBy = "",
                            Description = "Est sapiente aut quo nostrum ipsa.",
                            Directors = new List<string> { "ut", "omnis" },
                            DurationMinutes = 128,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=399",
                            Rating = 3.8081839761772263,
                            ReleaseDate = new DateTime(2019, 5, 15, 3, 53, 42, 742, DateTimeKind.Local).AddTicks(3932),
                            State = 4,
                            Title = "Ergonomic Soft Shoes",
                            TrailerUrl = "http://dax.net",
                            UpdatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 208, DateTimeKind.Utc).AddTicks(7400)
                        },
                        new
                        {
                            Id = new Guid("7e31d096-ae14-4934-91c3-daa7375ec31e"),
                            Cast = new List<string> { "voluptatem", "mollitia", "non", "quisquam", "perspiciatis", "cupiditate", "et" },
                            Country = "Haiti",
                            CreatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 208, DateTimeKind.Utc).AddTicks(7492),
                            CreatedBy = "",
                            Description = "Voluptatum perspiciatis enim perferendis et doloribus.",
                            Directors = new List<string> { "voluptate", "porro", "nostrum" },
                            DurationMinutes = 60,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=680",
                            Rating = 8.8532724259017055,
                            ReleaseDate = new DateTime(2016, 6, 16, 5, 41, 50, 259, DateTimeKind.Local).AddTicks(9693),
                            State = 4,
                            Title = "Fantastic Cotton Shoes",
                            TrailerUrl = "https://fabian.org",
                            UpdatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 208, DateTimeKind.Utc).AddTicks(7492)
                        },
                        new
                        {
                            Id = new Guid("6b5ae6a2-015c-4bfd-b1b0-921815341182"),
                            Cast = new List<string> { "debitis", "provident", "eos", "et", "vel", "eum", "quidem" },
                            Country = "British Indian Ocean Territory (Chagos Archipelago)",
                            CreatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 208, DateTimeKind.Utc).AddTicks(7588),
                            CreatedBy = "",
                            Description = "Maiores perferendis iusto velit et et.",
                            Directors = new List<string> { "vel", "sit", "quo" },
                            DurationMinutes = 128,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=216",
                            Rating = 7.7486604032958306,
                            ReleaseDate = new DateTime(2021, 1, 23, 1, 58, 25, 742, DateTimeKind.Local).AddTicks(1517),
                            State = 4,
                            Title = "Gorgeous Soft Towels",
                            TrailerUrl = "https://skylar.info",
                            UpdatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 208, DateTimeKind.Utc).AddTicks(7589)
                        },
                        new
                        {
                            Id = new Guid("79b0cb72-5b44-4351-beb8-2d56ef78cb82"),
                            Cast = new List<string> { "ipsum", "modi", "dicta", "quam", "ducimus" },
                            Country = "Ethiopia",
                            CreatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 208, DateTimeKind.Utc).AddTicks(7740),
                            CreatedBy = "",
                            Description = "Quas et aliquid blanditiis beatae sit quia.",
                            Directors = new List<string> { "aut" },
                            DurationMinutes = 66,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=635",
                            Rating = 8.7447750227894971,
                            ReleaseDate = new DateTime(2015, 10, 19, 10, 56, 56, 888, DateTimeKind.Local).AddTicks(7725),
                            State = 4,
                            Title = "Small Frozen Towels",
                            TrailerUrl = "https://ladarius.com",
                            UpdatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 208, DateTimeKind.Utc).AddTicks(7741)
                        },
                        new
                        {
                            Id = new Guid("c79feac3-0257-4301-9fc6-83616d64669e"),
                            Cast = new List<string> { "quisquam", "quia", "hic", "aut", "corporis" },
                            Country = "Micronesia",
                            CreatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 208, DateTimeKind.Utc).AddTicks(7837),
                            CreatedBy = "",
                            Description = "Autem incidunt sed aut.",
                            Directors = new List<string> { "quia" },
                            DurationMinutes = 76,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=97",
                            Rating = 7.308276878945918,
                            ReleaseDate = new DateTime(2016, 6, 29, 9, 41, 20, 90, DateTimeKind.Local).AddTicks(5231),
                            State = 4,
                            Title = "Rustic Frozen Hat",
                            TrailerUrl = "http://sven.name",
                            UpdatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 208, DateTimeKind.Utc).AddTicks(7837)
                        },
                        new
                        {
                            Id = new Guid("08685257-9ab3-4b38-985e-5e9d0d1fd323"),
                            Cast = new List<string> { "rerum", "magni", "sed", "facilis", "hic" },
                            Country = "Senegal",
                            CreatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 208, DateTimeKind.Utc).AddTicks(7958),
                            CreatedBy = "",
                            Description = "Numquam possimus fuga et et quia non dolores animi earum.",
                            Directors = new List<string> { "nobis" },
                            DurationMinutes = 135,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=449",
                            Rating = 9.5815753003732222,
                            ReleaseDate = new DateTime(2016, 3, 31, 12, 48, 39, 254, DateTimeKind.Local).AddTicks(468),
                            State = 4,
                            Title = "Awesome Cotton Gloves",
                            TrailerUrl = "http://jeffry.org",
                            UpdatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 208, DateTimeKind.Utc).AddTicks(7958)
                        },
                        new
                        {
                            Id = new Guid("064bebc3-3eac-4fe7-b94e-0b8540c0d7bb"),
                            Cast = new List<string> { "vitae", "sed", "autem" },
                            Country = "Suriname",
                            CreatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 208, DateTimeKind.Utc).AddTicks(8060),
                            CreatedBy = "",
                            Description = "Ut repellat iusto numquam et.",
                            Directors = new List<string> { "sed", "sed", "praesentium" },
                            DurationMinutes = 88,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=641",
                            Rating = 4.8206183113385421,
                            ReleaseDate = new DateTime(2017, 11, 5, 7, 37, 37, 158, DateTimeKind.Local).AddTicks(9556),
                            State = 4,
                            Title = "Licensed Concrete Car",
                            TrailerUrl = "http://stanley.net",
                            UpdatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 208, DateTimeKind.Utc).AddTicks(8061)
                        },
                        new
                        {
                            Id = new Guid("8993f58b-af85-4ffa-8fe4-1370560d8ca5"),
                            Cast = new List<string> { "enim", "iure", "facere", "sit", "sunt" },
                            Country = "Slovenia",
                            CreatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 208, DateTimeKind.Utc).AddTicks(8147),
                            CreatedBy = "",
                            Description = "Ipsam consequatur et voluptatem ut quidem provident.",
                            Directors = new List<string> { "sequi", "autem", "omnis" },
                            DurationMinutes = 174,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=858",
                            Rating = 5.7651474472816471,
                            ReleaseDate = new DateTime(2023, 5, 20, 14, 48, 14, 712, DateTimeKind.Local).AddTicks(5825),
                            State = 4,
                            Title = "Handmade Rubber Chicken",
                            TrailerUrl = "http://daphnee.com",
                            UpdatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 208, DateTimeKind.Utc).AddTicks(8147)
                        },
                        new
                        {
                            Id = new Guid("cedaa422-3a8f-4a21-80ba-655ae7256382"),
                            Cast = new List<string> { "unde", "autem", "quis", "omnis" },
                            Country = "Madagascar",
                            CreatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 208, DateTimeKind.Utc).AddTicks(8275),
                            CreatedBy = "",
                            Description = "Amet recusandae quis voluptas pariatur.",
                            Directors = new List<string> { "atque", "rerum", "rerum" },
                            DurationMinutes = 160,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=748",
                            Rating = 9.6855600842405849,
                            ReleaseDate = new DateTime(2016, 8, 5, 20, 51, 25, 32, DateTimeKind.Local).AddTicks(1780),
                            State = 4,
                            Title = "Awesome Rubber Pants",
                            TrailerUrl = "https://leilani.com",
                            UpdatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 208, DateTimeKind.Utc).AddTicks(8275)
                        },
                        new
                        {
                            Id = new Guid("6d70521a-a25c-41a2-8301-54b6fa4c684e"),
                            Cast = new List<string> { "vero", "totam", "culpa", "ullam" },
                            Country = "Peru",
                            CreatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 208, DateTimeKind.Utc).AddTicks(8362),
                            CreatedBy = "",
                            Description = "Aut est eligendi nesciunt ut amet natus voluptas tempora.",
                            Directors = new List<string> { "dicta", "ut" },
                            DurationMinutes = 180,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=919",
                            Rating = 5.2731072466757016,
                            ReleaseDate = new DateTime(2022, 4, 18, 14, 22, 56, 730, DateTimeKind.Local).AddTicks(4282),
                            State = 4,
                            Title = "Tasty Concrete Gloves",
                            TrailerUrl = "http://garry.com",
                            UpdatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 208, DateTimeKind.Utc).AddTicks(8362)
                        },
                        new
                        {
                            Id = new Guid("baf8b477-c6a4-4719-ba11-7fd7767f4c09"),
                            Cast = new List<string> { "recusandae", "facilis", "tenetur" },
                            Country = "United States of America",
                            CreatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 208, DateTimeKind.Utc).AddTicks(8459),
                            CreatedBy = "",
                            Description = "At omnis dolorem alias dolorem perferendis cum.",
                            Directors = new List<string> { "sequi", "cum", "veniam" },
                            DurationMinutes = 157,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=558",
                            Rating = 1.3741737426390088,
                            ReleaseDate = new DateTime(2019, 12, 31, 2, 12, 48, 761, DateTimeKind.Local).AddTicks(5144),
                            State = 4,
                            Title = "Handcrafted Granite Pants",
                            TrailerUrl = "http://savanna.name",
                            UpdatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 208, DateTimeKind.Utc).AddTicks(8459)
                        },
                        new
                        {
                            Id = new Guid("2d8d26c5-269f-4545-b327-9b6d37821a91"),
                            Cast = new List<string> { "vero", "sed", "quia", "exercitationem", "sed" },
                            Country = "Togo",
                            CreatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 208, DateTimeKind.Utc).AddTicks(8582),
                            CreatedBy = "",
                            Description = "In consequatur dignissimos quos qui cum dolores dignissimos quis perspiciatis.",
                            Directors = new List<string> { "perspiciatis", "qui", "quis" },
                            DurationMinutes = 63,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=1023",
                            Rating = 4.103978676321776,
                            ReleaseDate = new DateTime(2018, 9, 25, 8, 23, 1, 668, DateTimeKind.Local).AddTicks(403),
                            State = 4,
                            Title = "Unbranded Metal Shoes",
                            TrailerUrl = "http://khalil.info",
                            UpdatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 208, DateTimeKind.Utc).AddTicks(8583)
                        },
                        new
                        {
                            Id = new Guid("433d8913-1cc7-4f4c-a58b-dc7ad2f25996"),
                            Cast = new List<string> { "aut", "asperiores", "dolor", "voluptate", "impedit" },
                            Country = "Tuvalu",
                            CreatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 208, DateTimeKind.Utc).AddTicks(8682),
                            CreatedBy = "",
                            Description = "Alias voluptas aspernatur.",
                            Directors = new List<string> { "impedit", "animi" },
                            DurationMinutes = 67,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=1000",
                            Rating = 7.0992257504884879,
                            ReleaseDate = new DateTime(2019, 6, 24, 4, 43, 34, 243, DateTimeKind.Local).AddTicks(4492),
                            State = 4,
                            Title = "Sleek Fresh Salad",
                            TrailerUrl = "http://federico.biz",
                            UpdatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 208, DateTimeKind.Utc).AddTicks(8683)
                        },
                        new
                        {
                            Id = new Guid("7ebfd82b-5bc6-4278-b416-435460bcf08d"),
                            Cast = new List<string> { "non", "ut", "est", "maxime", "vel", "porro" },
                            Country = "Norfolk Island",
                            CreatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 208, DateTimeKind.Utc).AddTicks(8800),
                            CreatedBy = "",
                            Description = "Nulla est odio saepe corporis.",
                            Directors = new List<string> { "doloribus", "voluptatibus", "aliquam" },
                            DurationMinutes = 177,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=629",
                            Rating = 9.1919966389059162,
                            ReleaseDate = new DateTime(2022, 12, 10, 19, 38, 3, 388, DateTimeKind.Local).AddTicks(2564),
                            State = 4,
                            Title = "Sleek Metal Bacon",
                            TrailerUrl = "https://myrna.name",
                            UpdatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 208, DateTimeKind.Utc).AddTicks(8800)
                        },
                        new
                        {
                            Id = new Guid("4ab145ab-7a55-40cf-b7eb-9b322dd00440"),
                            Cast = new List<string> { "voluptas", "fugit", "aut", "cum", "est" },
                            Country = "Saint Barthelemy",
                            CreatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 208, DateTimeKind.Utc).AddTicks(8893),
                            CreatedBy = "",
                            Description = "Et sequi labore saepe qui dolores perspiciatis omnis.",
                            Directors = new List<string> { "sed", "qui", "nobis" },
                            DurationMinutes = 66,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=343",
                            Rating = 1.6699601625728777,
                            ReleaseDate = new DateTime(2022, 5, 14, 4, 23, 47, 857, DateTimeKind.Local).AddTicks(1908),
                            State = 4,
                            Title = "Generic Steel Pizza",
                            TrailerUrl = "https://felipe.net",
                            UpdatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 208, DateTimeKind.Utc).AddTicks(8893)
                        },
                        new
                        {
                            Id = new Guid("57905272-b8f4-40c9-8b10-e3f951dcf492"),
                            Cast = new List<string> { "odio", "et", "molestiae", "cupiditate" },
                            Country = "Moldova",
                            CreatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 208, DateTimeKind.Utc).AddTicks(8985),
                            CreatedBy = "",
                            Description = "A vel est vitae magni qui aut.",
                            Directors = new List<string> { "eligendi", "numquam" },
                            DurationMinutes = 116,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=658",
                            Rating = 6.5180796388743527,
                            ReleaseDate = new DateTime(2016, 6, 1, 1, 41, 27, 962, DateTimeKind.Local).AddTicks(8032),
                            State = 4,
                            Title = "Small Metal Cheese",
                            TrailerUrl = "http://glenna.org",
                            UpdatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 208, DateTimeKind.Utc).AddTicks(8985)
                        },
                        new
                        {
                            Id = new Guid("5d807638-ab8e-46e4-aa29-5c9b814c6e26"),
                            Cast = new List<string> { "libero", "repellat", "nemo", "itaque", "ut" },
                            Country = "Benin",
                            CreatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 208, DateTimeKind.Utc).AddTicks(9102),
                            CreatedBy = "",
                            Description = "Hic ea voluptates consectetur voluptas placeat.",
                            Directors = new List<string> { "impedit", "tempore", "enim" },
                            DurationMinutes = 88,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=237",
                            Rating = 5.9105181590091886,
                            ReleaseDate = new DateTime(2022, 1, 1, 20, 19, 1, 639, DateTimeKind.Local).AddTicks(3017),
                            State = 4,
                            Title = "Licensed Concrete Computer",
                            TrailerUrl = "https://taryn.org",
                            UpdatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 208, DateTimeKind.Utc).AddTicks(9103)
                        },
                        new
                        {
                            Id = new Guid("7d13699b-34f3-440a-9216-64d2f4e7c245"),
                            Cast = new List<string> { "delectus", "reprehenderit", "vitae", "modi", "voluptas", "deleniti" },
                            Country = "Saint Helena",
                            CreatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 208, DateTimeKind.Utc).AddTicks(9194),
                            CreatedBy = "",
                            Description = "Odio quidem facere mollitia.",
                            Directors = new List<string> { "eum", "minima" },
                            DurationMinutes = 105,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=605",
                            Rating = 9.2861288333971768,
                            ReleaseDate = new DateTime(2018, 6, 23, 9, 34, 46, 163, DateTimeKind.Local).AddTicks(8981),
                            State = 4,
                            Title = "Ergonomic Frozen Gloves",
                            TrailerUrl = "https://kolby.biz",
                            UpdatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 208, DateTimeKind.Utc).AddTicks(9195)
                        },
                        new
                        {
                            Id = new Guid("83ab1b0a-f083-4569-a1d7-1a955c6cfc74"),
                            Cast = new List<string> { "perferendis", "labore", "non" },
                            Country = "French Guiana",
                            CreatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 208, DateTimeKind.Utc).AddTicks(9308),
                            CreatedBy = "",
                            Description = "Esse aperiam reiciendis.",
                            Directors = new List<string> { "impedit", "tempora" },
                            DurationMinutes = 162,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=381",
                            Rating = 2.4508604230192153,
                            ReleaseDate = new DateTime(2020, 6, 20, 6, 9, 29, 15, DateTimeKind.Local).AddTicks(3602),
                            State = 4,
                            Title = "Refined Cotton Cheese",
                            TrailerUrl = "https://kendra.biz",
                            UpdatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 208, DateTimeKind.Utc).AddTicks(9309)
                        },
                        new
                        {
                            Id = new Guid("0623accb-f28a-4916-9536-17187189c2cb"),
                            Cast = new List<string> { "ut", "odit", "aut", "tempora" },
                            Country = "Saint Pierre and Miquelon",
                            CreatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 208, DateTimeKind.Utc).AddTicks(9387),
                            CreatedBy = "",
                            Description = "Iure ut nobis sed.",
                            Directors = new List<string> { "vel", "autem" },
                            DurationMinutes = 133,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=356",
                            Rating = 6.5550096277056795,
                            ReleaseDate = new DateTime(2018, 1, 1, 18, 27, 30, 112, DateTimeKind.Local).AddTicks(899),
                            State = 4,
                            Title = "Practical Wooden Shirt",
                            TrailerUrl = "https://nayeli.biz",
                            UpdatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 208, DateTimeKind.Utc).AddTicks(9388)
                        },
                        new
                        {
                            Id = new Guid("55617741-cf1c-4be0-b935-36a52d12164b"),
                            Cast = new List<string> { "delectus", "eligendi", "vel", "vitae", "et", "dolores", "molestiae" },
                            Country = "Palau",
                            CreatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 208, DateTimeKind.Utc).AddTicks(9681),
                            CreatedBy = "",
                            Description = "Non et minima vel maxime harum delectus debitis dicta dolore.",
                            Directors = new List<string> { "sunt", "rerum", "magni" },
                            DurationMinutes = 168,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=975",
                            Rating = 8.857711363909873,
                            ReleaseDate = new DateTime(2016, 11, 23, 21, 11, 28, 371, DateTimeKind.Local).AddTicks(2351),
                            State = 4,
                            Title = "Ergonomic Granite Gloves",
                            TrailerUrl = "https://maye.com",
                            UpdatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 208, DateTimeKind.Utc).AddTicks(9681)
                        },
                        new
                        {
                            Id = new Guid("d58df07f-c319-42f9-9c20-d628081e2fdd"),
                            Cast = new List<string> { "rerum", "id", "cum", "autem" },
                            Country = "Dominican Republic",
                            CreatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 208, DateTimeKind.Utc).AddTicks(9834),
                            CreatedBy = "",
                            Description = "Ab molestiae reprehenderit ducimus omnis.",
                            Directors = new List<string> { "voluptatem", "mollitia", "est" },
                            DurationMinutes = 109,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=206",
                            Rating = 7.6747008785911888,
                            ReleaseDate = new DateTime(2021, 10, 7, 6, 22, 2, 118, DateTimeKind.Local).AddTicks(1537),
                            State = 4,
                            Title = "Small Fresh Pizza",
                            TrailerUrl = "https://kathleen.net",
                            UpdatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 208, DateTimeKind.Utc).AddTicks(9835)
                        },
                        new
                        {
                            Id = new Guid("aad05fe9-016e-4cfc-a71d-017b5abb8fb5"),
                            Cast = new List<string> { "omnis", "alias", "aut", "aliquid" },
                            Country = "Lithuania",
                            CreatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 208, DateTimeKind.Utc).AddTicks(9922),
                            CreatedBy = "",
                            Description = "Dicta repellat tempora odio non voluptates ab.",
                            Directors = new List<string> { "quam", "qui" },
                            DurationMinutes = 73,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=210",
                            Rating = 4.3196664709470589,
                            ReleaseDate = new DateTime(2024, 3, 18, 18, 28, 45, 631, DateTimeKind.Local).AddTicks(1805),
                            State = 4,
                            Title = "Gorgeous Metal Hat",
                            TrailerUrl = "https://anibal.biz",
                            UpdatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 208, DateTimeKind.Utc).AddTicks(9922)
                        },
                        new
                        {
                            Id = new Guid("691c8cf6-5b56-4f8e-9081-77fec67e4c43"),
                            Cast = new List<string> { "aut", "corporis", "quibusdam", "accusamus", "pariatur", "quo", "aut" },
                            Country = "Panama",
                            CreatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 209, DateTimeKind.Utc).AddTicks(9),
                            CreatedBy = "",
                            Description = "Perferendis nihil quaerat cum voluptas voluptas natus non quia recusandae.",
                            Directors = new List<string> { "tenetur", "fugit", "error" },
                            DurationMinutes = 179,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=581",
                            Rating = 2.7234968264780917,
                            ReleaseDate = new DateTime(2020, 2, 26, 4, 44, 35, 155, DateTimeKind.Local).AddTicks(335),
                            State = 4,
                            Title = "Awesome Soft Cheese",
                            TrailerUrl = "https://pamela.biz",
                            UpdatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 209, DateTimeKind.Utc).AddTicks(9)
                        },
                        new
                        {
                            Id = new Guid("8cb7d1a6-3117-42e5-a1f0-4e55abffebcd"),
                            Cast = new List<string> { "aliquid", "ab", "sed", "quasi", "distinctio" },
                            Country = "French Guiana",
                            CreatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 209, DateTimeKind.Utc).AddTicks(156),
                            CreatedBy = "",
                            Description = "Aliquid enim magni quia iusto.",
                            Directors = new List<string> { "dolorem" },
                            DurationMinutes = 128,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=523",
                            Rating = 5.4923857257063116,
                            ReleaseDate = new DateTime(2023, 12, 5, 3, 16, 47, 75, DateTimeKind.Local).AddTicks(6744),
                            State = 4,
                            Title = "Ergonomic Soft Fish",
                            TrailerUrl = "http://gretchen.info",
                            UpdatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 209, DateTimeKind.Utc).AddTicks(157)
                        },
                        new
                        {
                            Id = new Guid("b5318ea2-1983-4a39-94d8-d84f5bd2b051"),
                            Cast = new List<string> { "ut", "dolor", "saepe", "rerum", "eligendi", "dolorum", "voluptatem" },
                            Country = "Rwanda",
                            CreatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 209, DateTimeKind.Utc).AddTicks(238),
                            CreatedBy = "",
                            Description = "Eos nostrum id eius quam.",
                            Directors = new List<string> { "facere", "laudantium" },
                            DurationMinutes = 79,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=434",
                            Rating = 1.0772013041719026,
                            ReleaseDate = new DateTime(2016, 4, 14, 14, 43, 34, 772, DateTimeKind.Local).AddTicks(4485),
                            State = 4,
                            Title = "Gorgeous Frozen Soap",
                            TrailerUrl = "https://stephen.com",
                            UpdatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 209, DateTimeKind.Utc).AddTicks(238)
                        },
                        new
                        {
                            Id = new Guid("f2cc4a85-4ffe-489d-a3e2-51489842f5e5"),
                            Cast = new List<string> { "vel", "non", "dolorem" },
                            Country = "Armenia",
                            CreatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 209, DateTimeKind.Utc).AddTicks(362),
                            CreatedBy = "",
                            Description = "Aut maiores iusto quo.",
                            Directors = new List<string> { "vel" },
                            DurationMinutes = 142,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=455",
                            Rating = 5.1410022654204157,
                            ReleaseDate = new DateTime(2021, 7, 11, 15, 26, 5, 727, DateTimeKind.Local).AddTicks(1516),
                            State = 4,
                            Title = "Sleek Rubber Computer",
                            TrailerUrl = "https://adele.net",
                            UpdatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 209, DateTimeKind.Utc).AddTicks(362)
                        },
                        new
                        {
                            Id = new Guid("326559af-505f-4c09-a851-a50d7339a7a4"),
                            Cast = new List<string> { "minus", "qui", "optio", "quia", "commodi" },
                            Country = "Bolivia",
                            CreatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 209, DateTimeKind.Utc).AddTicks(438),
                            CreatedBy = "",
                            Description = "Ut illo incidunt.",
                            Directors = new List<string> { "nihil" },
                            DurationMinutes = 168,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=776",
                            Rating = 4.2893877462188401,
                            ReleaseDate = new DateTime(2015, 11, 7, 2, 31, 47, 350, DateTimeKind.Local).AddTicks(8415),
                            State = 4,
                            Title = "Handcrafted Steel Tuna",
                            TrailerUrl = "https://emory.info",
                            UpdatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 209, DateTimeKind.Utc).AddTicks(438)
                        },
                        new
                        {
                            Id = new Guid("b3696ba3-4cf5-446c-a933-9f04325e0af4"),
                            Cast = new List<string> { "dolores", "voluptas", "repellendus" },
                            Country = "Bermuda",
                            CreatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 209, DateTimeKind.Utc).AddTicks(517),
                            CreatedBy = "",
                            Description = "Optio quisquam omnis deserunt et a eaque quo.",
                            Directors = new List<string> { "autem", "nesciunt" },
                            DurationMinutes = 82,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=430",
                            Rating = 3.3083993104425287,
                            ReleaseDate = new DateTime(2015, 8, 31, 3, 11, 40, 137, DateTimeKind.Local).AddTicks(8281),
                            State = 4,
                            Title = "Incredible Rubber Bacon",
                            TrailerUrl = "https://cicero.info",
                            UpdatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 209, DateTimeKind.Utc).AddTicks(517)
                        },
                        new
                        {
                            Id = new Guid("0619017f-65e8-423f-8f86-0721ea1a1e75"),
                            Cast = new List<string> { "sunt", "ea", "in", "quo", "quia", "ullam", "excepturi" },
                            Country = "Serbia",
                            CreatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 209, DateTimeKind.Utc).AddTicks(636),
                            CreatedBy = "",
                            Description = "Vero et consequatur minima excepturi consequatur.",
                            Directors = new List<string> { "reprehenderit" },
                            DurationMinutes = 176,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=835",
                            Rating = 8.2393138685041443,
                            ReleaseDate = new DateTime(2019, 1, 17, 6, 24, 7, 313, DateTimeKind.Local).AddTicks(4549),
                            State = 4,
                            Title = "Handcrafted Steel Bike",
                            TrailerUrl = "https://kelli.org",
                            UpdatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 209, DateTimeKind.Utc).AddTicks(636)
                        },
                        new
                        {
                            Id = new Guid("5ac68a6f-f7a3-47c7-9a99-d5f00d0d4463"),
                            Cast = new List<string> { "et", "ducimus", "omnis", "ea", "officia", "quia" },
                            Country = "India",
                            CreatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 209, DateTimeKind.Utc).AddTicks(725),
                            CreatedBy = "",
                            Description = "Consectetur incidunt enim ut inventore explicabo natus minima ad.",
                            Directors = new List<string> { "possimus", "sed" },
                            DurationMinutes = 87,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=613",
                            Rating = 4.9991665892790671,
                            ReleaseDate = new DateTime(2023, 8, 23, 16, 49, 36, 697, DateTimeKind.Local).AddTicks(8013),
                            State = 4,
                            Title = "Practical Fresh Chair",
                            TrailerUrl = "http://dexter.net",
                            UpdatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 209, DateTimeKind.Utc).AddTicks(725)
                        },
                        new
                        {
                            Id = new Guid("85c26379-fca0-49a6-8b83-46c23bc7297f"),
                            Cast = new List<string> { "laborum", "blanditiis", "quos" },
                            Country = "Virgin Islands, British",
                            CreatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 209, DateTimeKind.Utc).AddTicks(822),
                            CreatedBy = "",
                            Description = "Quae pariatur dolorem architecto minima quidem odio et vel.",
                            Directors = new List<string> { "et", "provident" },
                            DurationMinutes = 175,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=743",
                            Rating = 6.4077944724350147,
                            ReleaseDate = new DateTime(2016, 6, 29, 4, 45, 16, 32, DateTimeKind.Local).AddTicks(4849),
                            State = 4,
                            Title = "Incredible Steel Chicken",
                            TrailerUrl = "https://ressie.net",
                            UpdatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 209, DateTimeKind.Utc).AddTicks(823)
                        },
                        new
                        {
                            Id = new Guid("17befff2-594b-4fe8-acb1-79d2edc110ef"),
                            Cast = new List<string> { "id", "error", "odit", "ea", "qui" },
                            Country = "Uzbekistan",
                            CreatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 209, DateTimeKind.Utc).AddTicks(948),
                            CreatedBy = "",
                            Description = "Quas et quibusdam nesciunt qui voluptatem aliquid non.",
                            Directors = new List<string> { "dolorem", "eos" },
                            DurationMinutes = 163,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=83",
                            Rating = 6.4307417996240002,
                            ReleaseDate = new DateTime(2017, 5, 26, 9, 36, 30, 107, DateTimeKind.Local).AddTicks(9158),
                            State = 4,
                            Title = "Practical Metal Sausages",
                            TrailerUrl = "https://charlie.name",
                            UpdatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 209, DateTimeKind.Utc).AddTicks(949)
                        },
                        new
                        {
                            Id = new Guid("94f294e6-0945-4a95-b079-0f3542ef3d04"),
                            Cast = new List<string> { "veritatis", "suscipit", "labore", "consequuntur", "qui" },
                            Country = "French Polynesia",
                            CreatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 209, DateTimeKind.Utc).AddTicks(1038),
                            CreatedBy = "",
                            Description = "Neque reiciendis omnis minima ex.",
                            Directors = new List<string> { "repudiandae", "aliquid" },
                            DurationMinutes = 88,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=171",
                            Rating = 6.0615843030292922,
                            ReleaseDate = new DateTime(2019, 3, 19, 15, 28, 31, 824, DateTimeKind.Local).AddTicks(3386),
                            State = 4,
                            Title = "Intelligent Metal Towels",
                            TrailerUrl = "http://augustus.net",
                            UpdatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 209, DateTimeKind.Utc).AddTicks(1039)
                        },
                        new
                        {
                            Id = new Guid("da8077bf-1ca8-4815-b25b-77d4ed64fc4b"),
                            Cast = new List<string> { "velit", "minima", "officia", "est" },
                            Country = "French Guiana",
                            CreatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 209, DateTimeKind.Utc).AddTicks(1218),
                            CreatedBy = "",
                            Description = "Veritatis hic aut beatae sapiente sequi.",
                            Directors = new List<string> { "itaque" },
                            DurationMinutes = 169,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=150",
                            Rating = 7.7432073677448905,
                            ReleaseDate = new DateTime(2025, 4, 2, 22, 35, 53, 388, DateTimeKind.Local).AddTicks(467),
                            State = 4,
                            Title = "Tasty Cotton Fish",
                            TrailerUrl = "https://jayson.org",
                            UpdatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 209, DateTimeKind.Utc).AddTicks(1219)
                        },
                        new
                        {
                            Id = new Guid("cb34c34c-269a-441c-8cc8-77ba928d6780"),
                            Cast = new List<string> { "accusamus", "similique", "accusamus" },
                            Country = "Nicaragua",
                            CreatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 209, DateTimeKind.Utc).AddTicks(1302),
                            CreatedBy = "",
                            Description = "Possimus itaque accusantium mollitia minima illo eligendi rem harum quidem.",
                            Directors = new List<string> { "aut", "itaque", "minus" },
                            DurationMinutes = 137,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=236",
                            Rating = 6.7761523521183626,
                            ReleaseDate = new DateTime(2015, 11, 17, 8, 13, 53, 510, DateTimeKind.Local).AddTicks(1513),
                            State = 4,
                            Title = "Rustic Soft Table",
                            TrailerUrl = "http://terrell.net",
                            UpdatedAt = new DateTime(2025, 5, 13, 2, 34, 40, 209, DateTimeKind.Utc).AddTicks(1302)
                        });
                });

            modelBuilder.Entity("Firebase_Auth.Data.Entities.Authentication.RolePermission", b =>
                {
                    b.HasOne("Firebase_Auth.Data.Entities.Authentication.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Firebase_Auth.Data.Entities.Authentication.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Firebase_Auth.Data.Entities.Authentication.User", b =>
                {
                    b.HasOne("Firebase_Auth.Data.Entities.Authentication.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Firebase_Auth.Data.Entities.Authentication.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Firebase_Auth.Data.Entities.Authentication.Role", b =>
                {
                    b.Navigation("RolePermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
