// <auto-generated />
using System;
using System.Collections.Generic;
using Firebase_Auth.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace firebase_auth.Migrations
{
    [DbContext(typeof(CoreDbContext))]
    [Migration("20250423061157_RolePermissionSetUp")]
    partial class RolePermissionSetUp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Firebase_Auth.Data.Entities.Authentication.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Code = "CreateContent",
                            Description = "Permission to create content",
                            Name = "CreateContent",
                            State = 4
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Code = "EditContent",
                            Description = "Permission to edit content",
                            Name = "EditContent",
                            State = 4
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Code = "DeleteContent",
                            Description = "Permission to delete content",
                            Name = "DeleteContent",
                            State = 4
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Code = "ViewContent",
                            Description = "Permission to view content",
                            Name = "ViewContent",
                            State = 4
                        });
                });

            modelBuilder.Entity("Firebase_Auth.Data.Entities.Authentication.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Administrator role with full permissions",
                            Name = "admin",
                            State = 4
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Description = "Editor role with editing permissions",
                            Name = "moderator",
                            State = 4
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Description = "User role with viewing permissions",
                            Name = "user",
                            State = 4
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            Description = "Root",
                            Name = "root",
                            State = 4
                        });
                });

            modelBuilder.Entity("Firebase_Auth.Data.Entities.Authentication.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("99999999-9999-9999-9999-999999999999"),
                            PermissionId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            RoleId = new Guid("99999999-9999-9999-9999-999999999999"),
                            PermissionId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            RoleId = new Guid("99999999-9999-9999-9999-999999999999"),
                            PermissionId = new Guid("66666666-6666-6666-6666-666666666666")
                        },
                        new
                        {
                            RoleId = new Guid("99999999-9999-9999-9999-999999999999"),
                            PermissionId = new Guid("77777777-7777-7777-7777-777777777777")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("66666666-6666-6666-6666-666666666666")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("77777777-7777-7777-7777-777777777777")
                        },
                        new
                        {
                            RoleId = new Guid("22222222-2222-2222-2222-222222222222"),
                            PermissionId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            RoleId = new Guid("22222222-2222-2222-2222-222222222222"),
                            PermissionId = new Guid("77777777-7777-7777-7777-777777777777")
                        },
                        new
                        {
                            RoleId = new Guid("33333333-3333-3333-3333-333333333333"),
                            PermissionId = new Guid("77777777-7777-7777-7777-777777777777")
                        });
                });

            modelBuilder.Entity("Firebase_Auth.Data.Entities.Authentication.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdditionalData")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FirebaseUid")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("FullName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("FirebaseUid")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Firebase_Auth.Data.Entities.Movies.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<string>>("Cast")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Directors")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Language")
                        .HasColumnType("text");

                    b.Property<string>("PosterUrl")
                        .HasColumnType("text");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TrailerUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("01ab700c-88de-4efe-b2cf-bea2f852ff90"),
                            Cast = new List<string> { "ea", "dolores", "et", "facilis", "aut" },
                            Country = "Mayotte",
                            CreatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 409, DateTimeKind.Utc).AddTicks(5418),
                            CreatedBy = "",
                            Description = "Eligendi a est.",
                            Directors = new List<string> { "sunt", "accusamus", "ad" },
                            DurationMinutes = 147,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=1025",
                            Rating = 3.3740443197631134,
                            ReleaseDate = new DateTime(2021, 1, 28, 22, 44, 42, 634, DateTimeKind.Local).AddTicks(2542),
                            State = 4,
                            Title = "Practical Soft Table",
                            TrailerUrl = "https://francesco.name",
                            UpdatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 409, DateTimeKind.Utc).AddTicks(5423)
                        },
                        new
                        {
                            Id = new Guid("ab98e21f-b122-4ef3-b785-08e8feda65ad"),
                            Cast = new List<string> { "commodi", "laudantium", "ea", "rerum", "dolores" },
                            Country = "Belize",
                            CreatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 418, DateTimeKind.Utc).AddTicks(6041),
                            CreatedBy = "",
                            Description = "Debitis incidunt autem quam quia culpa.",
                            Directors = new List<string> { "rerum", "enim" },
                            DurationMinutes = 114,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=24",
                            Rating = 2.0577940681032088,
                            ReleaseDate = new DateTime(2018, 8, 28, 9, 37, 25, 59, DateTimeKind.Local).AddTicks(5801),
                            State = 4,
                            Title = "Intelligent Fresh Bike",
                            TrailerUrl = "https://alberto.name",
                            UpdatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 418, DateTimeKind.Utc).AddTicks(6044)
                        },
                        new
                        {
                            Id = new Guid("df19fb21-2ee1-493c-837d-680fb5ee8f6f"),
                            Cast = new List<string> { "soluta", "fuga", "nihil", "molestias", "aut", "quae" },
                            Country = "Nigeria",
                            CreatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 418, DateTimeKind.Utc).AddTicks(6922),
                            CreatedBy = "",
                            Description = "Ab temporibus dolor autem non iure similique.",
                            Directors = new List<string> { "consequatur" },
                            DurationMinutes = 62,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=1075",
                            Rating = 1.7593031889849295,
                            ReleaseDate = new DateTime(2024, 2, 7, 7, 55, 1, 616, DateTimeKind.Local).AddTicks(4316),
                            State = 4,
                            Title = "Refined Plastic Bacon",
                            TrailerUrl = "https://mallory.info",
                            UpdatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 418, DateTimeKind.Utc).AddTicks(6923)
                        },
                        new
                        {
                            Id = new Guid("ec12d0d3-1e39-4bca-af24-dd3158c4a2ef"),
                            Cast = new List<string> { "omnis", "saepe", "hic", "nobis", "eos" },
                            Country = "Trinidad and Tobago",
                            CreatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 418, DateTimeKind.Utc).AddTicks(7124),
                            CreatedBy = "",
                            Description = "Corrupti pariatur omnis aut pariatur et sunt.",
                            Directors = new List<string> { "magnam", "vero" },
                            DurationMinutes = 125,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=523",
                            Rating = 6.9575613823269506,
                            ReleaseDate = new DateTime(2020, 12, 24, 6, 37, 26, 251, DateTimeKind.Local).AddTicks(8199),
                            State = 4,
                            Title = "Rustic Frozen Bike",
                            TrailerUrl = "https://everett.name",
                            UpdatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 418, DateTimeKind.Utc).AddTicks(7124)
                        },
                        new
                        {
                            Id = new Guid("f99ae8d7-70a8-4cbc-84bb-1c1b95f74ce1"),
                            Cast = new List<string> { "odit", "dolore", "enim" },
                            Country = "Iceland",
                            CreatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 418, DateTimeKind.Utc).AddTicks(7235),
                            CreatedBy = "",
                            Description = "Expedita alias quisquam vel impedit fugit ducimus quaerat ut.",
                            Directors = new List<string> { "et", "cumque", "quos" },
                            DurationMinutes = 103,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=71",
                            Rating = 9.6705201834514547,
                            ReleaseDate = new DateTime(2018, 11, 10, 6, 17, 44, 124, DateTimeKind.Local).AddTicks(7444),
                            State = 4,
                            Title = "Practical Metal Pants",
                            TrailerUrl = "http://fabiola.name",
                            UpdatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 418, DateTimeKind.Utc).AddTicks(7236)
                        },
                        new
                        {
                            Id = new Guid("6acc018d-d453-4339-b2cd-87a71db7313e"),
                            Cast = new List<string> { "qui", "cupiditate", "aut" },
                            Country = "Slovakia (Slovak Republic)",
                            CreatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 418, DateTimeKind.Utc).AddTicks(7341),
                            CreatedBy = "",
                            Description = "Voluptatibus quia officiis sint porro itaque est.",
                            Directors = new List<string> { "esse", "libero", "repellendus" },
                            DurationMinutes = 103,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=860",
                            Rating = 3.5180668486254612,
                            ReleaseDate = new DateTime(2015, 9, 18, 5, 39, 32, 237, DateTimeKind.Local).AddTicks(5732),
                            State = 4,
                            Title = "Intelligent Granite Sausages",
                            TrailerUrl = "http://lea.name",
                            UpdatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 418, DateTimeKind.Utc).AddTicks(7342)
                        },
                        new
                        {
                            Id = new Guid("eadd08a2-26ef-44eb-a922-a8aebefe3807"),
                            Cast = new List<string> { "debitis", "aliquid", "ullam", "minus", "voluptas" },
                            Country = "Iran",
                            CreatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 418, DateTimeKind.Utc).AddTicks(7534),
                            CreatedBy = "",
                            Description = "Adipisci tempora quo earum explicabo modi omnis laborum.",
                            Directors = new List<string> { "aperiam", "libero", "fugiat" },
                            DurationMinutes = 158,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=950",
                            Rating = 1.2998497126390438,
                            ReleaseDate = new DateTime(2024, 11, 1, 2, 15, 59, 174, DateTimeKind.Local).AddTicks(628),
                            State = 4,
                            Title = "Ergonomic Plastic Chair",
                            TrailerUrl = "http://griffin.biz",
                            UpdatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 418, DateTimeKind.Utc).AddTicks(7534)
                        },
                        new
                        {
                            Id = new Guid("9e18c30e-5150-4041-a7c9-a4225365f497"),
                            Cast = new List<string> { "eligendi", "aliquam", "mollitia", "et", "et", "aliquam" },
                            Country = "United States Minor Outlying Islands",
                            CreatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 418, DateTimeKind.Utc).AddTicks(7642),
                            CreatedBy = "",
                            Description = "Ut nihil quibusdam tempore sed totam delectus odio.",
                            Directors = new List<string> { "odit", "omnis" },
                            DurationMinutes = 61,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=588",
                            Rating = 6.5386440625600457,
                            ReleaseDate = new DateTime(2016, 7, 15, 9, 57, 22, 314, DateTimeKind.Local).AddTicks(9669),
                            State = 4,
                            Title = "Incredible Soft Chair",
                            TrailerUrl = "https://leonora.biz",
                            UpdatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 418, DateTimeKind.Utc).AddTicks(7643)
                        },
                        new
                        {
                            Id = new Guid("d3f26485-dddc-4c09-a637-eb20a9a4c8d3"),
                            Cast = new List<string> { "ut", "est", "et", "dolor", "optio", "fuga", "aperiam" },
                            Country = "Samoa",
                            CreatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 418, DateTimeKind.Utc).AddTicks(7827),
                            CreatedBy = "",
                            Description = "In facilis rerum et iste.",
                            Directors = new List<string> { "ea", "ipsum", "porro" },
                            DurationMinutes = 113,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=764",
                            Rating = 5.8439559066519031,
                            ReleaseDate = new DateTime(2017, 10, 28, 21, 52, 47, 573, DateTimeKind.Local).AddTicks(6532),
                            State = 4,
                            Title = "Ergonomic Fresh Chips",
                            TrailerUrl = "http://gabrielle.net",
                            UpdatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 418, DateTimeKind.Utc).AddTicks(7828)
                        },
                        new
                        {
                            Id = new Guid("0efda013-d623-4e26-808e-ce5d801d0c21"),
                            Cast = new List<string> { "enim", "aliquam", "quia" },
                            Country = "Australia",
                            CreatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 418, DateTimeKind.Utc).AddTicks(7929),
                            CreatedBy = "",
                            Description = "Autem aperiam temporibus officiis amet laborum.",
                            Directors = new List<string> { "eaque" },
                            DurationMinutes = 133,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=956",
                            Rating = 5.6608665310704662,
                            ReleaseDate = new DateTime(2022, 9, 24, 16, 47, 51, 518, DateTimeKind.Local).AddTicks(8438),
                            State = 4,
                            Title = "Ergonomic Steel Gloves",
                            TrailerUrl = "http://theresa.info",
                            UpdatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 418, DateTimeKind.Utc).AddTicks(7929)
                        },
                        new
                        {
                            Id = new Guid("35d5b1e8-27af-4425-9697-86612826d3b4"),
                            Cast = new List<string> { "distinctio", "debitis", "nemo", "corporis", "fugiat", "veritatis", "saepe" },
                            Country = "Rwanda",
                            CreatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 418, DateTimeKind.Utc).AddTicks(8010),
                            CreatedBy = "",
                            Description = "Et at eos natus natus nisi nisi at consequatur.",
                            Directors = new List<string> { "dolorum", "laboriosam", "est" },
                            DurationMinutes = 148,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=632",
                            Rating = 8.6695401050173047,
                            ReleaseDate = new DateTime(2019, 10, 26, 1, 25, 15, 806, DateTimeKind.Local).AddTicks(5896),
                            State = 4,
                            Title = "Awesome Concrete Fish",
                            TrailerUrl = "https://dallas.com",
                            UpdatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 418, DateTimeKind.Utc).AddTicks(8010)
                        },
                        new
                        {
                            Id = new Guid("45797d12-58ba-4099-88fa-e5008cbde9a1"),
                            Cast = new List<string> { "blanditiis", "provident", "possimus" },
                            Country = "Iraq",
                            CreatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 418, DateTimeKind.Utc).AddTicks(8152),
                            CreatedBy = "",
                            Description = "Recusandae et laboriosam totam deserunt.",
                            Directors = new List<string> { "eum" },
                            DurationMinutes = 155,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=232",
                            Rating = 7.7891384573344755,
                            ReleaseDate = new DateTime(2021, 11, 29, 15, 5, 7, 733, DateTimeKind.Local).AddTicks(2925),
                            State = 4,
                            Title = "Tasty Wooden Gloves",
                            TrailerUrl = "https://oral.org",
                            UpdatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 418, DateTimeKind.Utc).AddTicks(8153)
                        },
                        new
                        {
                            Id = new Guid("4340b7c2-77c2-4740-aa7d-4dc53050c9fc"),
                            Cast = new List<string> { "rem", "doloremque", "sit", "non", "quis", "eum" },
                            Country = "Faroe Islands",
                            CreatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 418, DateTimeKind.Utc).AddTicks(8234),
                            CreatedBy = "",
                            Description = "Debitis facilis porro dolor totam illum non sed incidunt.",
                            Directors = new List<string> { "quidem", "vitae" },
                            DurationMinutes = 97,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=409",
                            Rating = 1.9902396764268702,
                            ReleaseDate = new DateTime(2022, 9, 30, 5, 3, 41, 952, DateTimeKind.Local).AddTicks(1020),
                            State = 4,
                            Title = "Intelligent Frozen Hat",
                            TrailerUrl = "https://johathan.com",
                            UpdatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 418, DateTimeKind.Utc).AddTicks(8235)
                        },
                        new
                        {
                            Id = new Guid("de94b9fa-df58-4454-9701-dcedb4a00b10"),
                            Cast = new List<string> { "eum", "omnis", "laboriosam", "et", "mollitia", "dicta" },
                            Country = "Kuwait",
                            CreatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 418, DateTimeKind.Utc).AddTicks(8369),
                            CreatedBy = "",
                            Description = "Cupiditate aliquid vero molestiae quibusdam harum eligendi fugiat tenetur.",
                            Directors = new List<string> { "ut", "quasi", "quasi" },
                            DurationMinutes = 66,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=378",
                            Rating = 2.8137303871386496,
                            ReleaseDate = new DateTime(2025, 3, 30, 13, 38, 22, 197, DateTimeKind.Local).AddTicks(3550),
                            State = 4,
                            Title = "Handcrafted Concrete Pizza",
                            TrailerUrl = "https://rico.net",
                            UpdatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 418, DateTimeKind.Utc).AddTicks(8370)
                        },
                        new
                        {
                            Id = new Guid("467ab48a-9936-47ad-8c4f-dd41d190036d"),
                            Cast = new List<string> { "ad", "sunt", "qui", "odit", "deleniti" },
                            Country = "Jamaica",
                            CreatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 418, DateTimeKind.Utc).AddTicks(8472),
                            CreatedBy = "",
                            Description = "Odio saepe ut dolores dolor.",
                            Directors = new List<string> { "et" },
                            DurationMinutes = 98,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=376",
                            Rating = 1.0278399883468889,
                            ReleaseDate = new DateTime(2015, 9, 2, 18, 13, 6, 948, DateTimeKind.Local).AddTicks(5713),
                            State = 4,
                            Title = "Handcrafted Cotton Shirt",
                            TrailerUrl = "http://dorcas.info",
                            UpdatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 418, DateTimeKind.Utc).AddTicks(8473)
                        },
                        new
                        {
                            Id = new Guid("df377ad6-0e2d-4237-a1bd-c4140c652f4f"),
                            Cast = new List<string> { "mollitia", "quia", "rerum" },
                            Country = "Georgia",
                            CreatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 418, DateTimeKind.Utc).AddTicks(8558),
                            CreatedBy = "",
                            Description = "Deleniti occaecati quia nesciunt omnis earum omnis optio eaque.",
                            Directors = new List<string> { "ratione", "aspernatur" },
                            DurationMinutes = 100,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=256",
                            Rating = 2.9087275055096811,
                            ReleaseDate = new DateTime(2020, 4, 9, 4, 2, 27, 892, DateTimeKind.Local).AddTicks(1713),
                            State = 4,
                            Title = "Refined Cotton Mouse",
                            TrailerUrl = "http://shaun.biz",
                            UpdatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 418, DateTimeKind.Utc).AddTicks(8559)
                        },
                        new
                        {
                            Id = new Guid("c4e370b6-c78d-4b4b-9a53-f056d9763e8c"),
                            Cast = new List<string> { "qui", "sequi", "non", "deleniti" },
                            Country = "Ecuador",
                            CreatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 418, DateTimeKind.Utc).AddTicks(8681),
                            CreatedBy = "",
                            Description = "Consequatur corporis aliquid atque dignissimos possimus rerum.",
                            Directors = new List<string> { "voluptate", "veniam" },
                            DurationMinutes = 128,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=344",
                            Rating = 3.0298223636041319,
                            ReleaseDate = new DateTime(2017, 12, 1, 13, 31, 54, 516, DateTimeKind.Local).AddTicks(8782),
                            State = 4,
                            Title = "Generic Granite Keyboard",
                            TrailerUrl = "http://tiara.com",
                            UpdatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 418, DateTimeKind.Utc).AddTicks(8681)
                        },
                        new
                        {
                            Id = new Guid("5a9da924-f75b-4f83-af5e-b29f1223ae18"),
                            Cast = new List<string> { "dolores", "veniam", "est", "aliquam" },
                            Country = "Lao People's Democratic Republic",
                            CreatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 418, DateTimeKind.Utc).AddTicks(8769),
                            CreatedBy = "",
                            Description = "Aut ipsum qui.",
                            Directors = new List<string> { "porro" },
                            DurationMinutes = 138,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=403",
                            Rating = 4.9846128550106048,
                            ReleaseDate = new DateTime(2015, 9, 15, 2, 19, 25, 685, DateTimeKind.Local).AddTicks(5856),
                            State = 4,
                            Title = "Small Plastic Sausages",
                            TrailerUrl = "https://austin.org",
                            UpdatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 418, DateTimeKind.Utc).AddTicks(8770)
                        },
                        new
                        {
                            Id = new Guid("f39e7790-e51a-4be5-9a48-eb32a9453599"),
                            Cast = new List<string> { "laudantium", "quo", "ducimus" },
                            Country = "Saint Vincent and the Grenadines",
                            CreatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 418, DateTimeKind.Utc).AddTicks(8845),
                            CreatedBy = "",
                            Description = "Minima provident et omnis sit iure nulla impedit qui sunt.",
                            Directors = new List<string> { "magnam" },
                            DurationMinutes = 113,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=163",
                            Rating = 2.3130585140690068,
                            ReleaseDate = new DateTime(2023, 7, 4, 9, 12, 40, 614, DateTimeKind.Local).AddTicks(5254),
                            State = 4,
                            Title = "Small Concrete Table",
                            TrailerUrl = "http://hilma.name",
                            UpdatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 418, DateTimeKind.Utc).AddTicks(8845)
                        },
                        new
                        {
                            Id = new Guid("f969900b-8ba7-4192-a014-f6f5df7fa68d"),
                            Cast = new List<string> { "ut", "accusantium", "similique", "et" },
                            Country = "Taiwan",
                            CreatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 418, DateTimeKind.Utc).AddTicks(8965),
                            CreatedBy = "",
                            Description = "Praesentium non non omnis ad consequuntur quas quam.",
                            Directors = new List<string> { "labore", "perferendis" },
                            DurationMinutes = 71,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=968",
                            Rating = 5.4364651380717657,
                            ReleaseDate = new DateTime(2017, 7, 21, 5, 21, 18, 60, DateTimeKind.Local).AddTicks(9126),
                            State = 4,
                            Title = "Awesome Fresh Fish",
                            TrailerUrl = "https://marques.org",
                            UpdatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 418, DateTimeKind.Utc).AddTicks(8965)
                        },
                        new
                        {
                            Id = new Guid("cc0aac27-7270-4cb4-a34d-9e9ac1aa668c"),
                            Cast = new List<string> { "dolor", "sunt", "omnis", "repellat", "nemo", "sed", "distinctio" },
                            Country = "Equatorial Guinea",
                            CreatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 418, DateTimeKind.Utc).AddTicks(9060),
                            CreatedBy = "",
                            Description = "Illum et perspiciatis neque et.",
                            Directors = new List<string> { "sequi" },
                            DurationMinutes = 60,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=221",
                            Rating = 7.5920919447792343,
                            ReleaseDate = new DateTime(2021, 4, 25, 2, 34, 17, 652, DateTimeKind.Local).AddTicks(280),
                            State = 4,
                            Title = "Licensed Granite Towels",
                            TrailerUrl = "https://romaine.name",
                            UpdatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 418, DateTimeKind.Utc).AddTicks(9061)
                        },
                        new
                        {
                            Id = new Guid("69849795-5c8c-41d2-a8ef-74da71645fc2"),
                            Cast = new List<string> { "est", "beatae", "qui", "incidunt", "ea", "omnis", "sit" },
                            Country = "Niue",
                            CreatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 418, DateTimeKind.Utc).AddTicks(9174),
                            CreatedBy = "",
                            Description = "Adipisci aliquid cumque est et.",
                            Directors = new List<string> { "quod", "harum", "eum" },
                            DurationMinutes = 96,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=662",
                            Rating = 1.7446939675713788,
                            ReleaseDate = new DateTime(2023, 10, 6, 2, 18, 12, 410, DateTimeKind.Local).AddTicks(4264),
                            State = 4,
                            Title = "Handmade Granite Fish",
                            TrailerUrl = "https://elna.name",
                            UpdatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 418, DateTimeKind.Utc).AddTicks(9174)
                        },
                        new
                        {
                            Id = new Guid("afd44a2e-e7c2-4610-b174-7d2a8ffa9c69"),
                            Cast = new List<string> { "sed", "velit", "atque", "molestiae" },
                            Country = "Bermuda",
                            CreatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 418, DateTimeKind.Utc).AddTicks(9266),
                            CreatedBy = "",
                            Description = "Et sequi quis eos cum quo.",
                            Directors = new List<string> { "deleniti" },
                            DurationMinutes = 105,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=394",
                            Rating = 4.8016912979642967,
                            ReleaseDate = new DateTime(2018, 6, 10, 3, 53, 49, 682, DateTimeKind.Local).AddTicks(8481),
                            State = 4,
                            Title = "Rustic Cotton Cheese",
                            TrailerUrl = "http://henderson.biz",
                            UpdatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 418, DateTimeKind.Utc).AddTicks(9266)
                        },
                        new
                        {
                            Id = new Guid("f741dddc-36ce-4db9-81f4-2d3989882966"),
                            Cast = new List<string> { "cupiditate", "perferendis", "maxime", "est", "nobis", "dicta", "voluptatem" },
                            Country = "Greece",
                            CreatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 418, DateTimeKind.Utc).AddTicks(9348),
                            CreatedBy = "",
                            Description = "Aut deserunt in et aut architecto quos suscipit in.",
                            Directors = new List<string> { "nam", "vitae" },
                            DurationMinutes = 74,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=1045",
                            Rating = 7.9965380628817337,
                            ReleaseDate = new DateTime(2015, 7, 14, 5, 1, 29, 487, DateTimeKind.Local).AddTicks(5246),
                            State = 4,
                            Title = "Intelligent Frozen Gloves",
                            TrailerUrl = "http://jennifer.name",
                            UpdatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 418, DateTimeKind.Utc).AddTicks(9348)
                        },
                        new
                        {
                            Id = new Guid("107a6a0c-ee3d-43c9-890d-781d057775cc"),
                            Cast = new List<string> { "cupiditate", "rem", "magni", "optio" },
                            Country = "Lebanon",
                            CreatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 418, DateTimeKind.Utc).AddTicks(9513),
                            CreatedBy = "",
                            Description = "Distinctio earum est modi similique voluptas earum.",
                            Directors = new List<string> { "debitis", "reiciendis" },
                            DurationMinutes = 168,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=621",
                            Rating = 1.9876937043962823,
                            ReleaseDate = new DateTime(2024, 7, 12, 9, 31, 57, 959, DateTimeKind.Local).AddTicks(4271),
                            State = 4,
                            Title = "Handmade Wooden Chips",
                            TrailerUrl = "https://richie.biz",
                            UpdatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 418, DateTimeKind.Utc).AddTicks(9514)
                        },
                        new
                        {
                            Id = new Guid("28b0a778-962f-4cc4-8d3d-953cb9a2020d"),
                            Cast = new List<string> { "exercitationem", "beatae", "error", "omnis" },
                            Country = "Senegal",
                            CreatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 418, DateTimeKind.Utc).AddTicks(9598),
                            CreatedBy = "",
                            Description = "Fugit fugit blanditiis qui provident eius maxime sint.",
                            Directors = new List<string> { "ut" },
                            DurationMinutes = 107,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=165",
                            Rating = 7.8105480403785332,
                            ReleaseDate = new DateTime(2018, 8, 26, 17, 44, 49, 593, DateTimeKind.Local).AddTicks(2043),
                            State = 4,
                            Title = "Awesome Wooden Ball",
                            TrailerUrl = "https://axel.biz",
                            UpdatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 418, DateTimeKind.Utc).AddTicks(9598)
                        },
                        new
                        {
                            Id = new Guid("8d3653f3-71b6-48f8-b1a0-2aeeaf74a5ef"),
                            Cast = new List<string> { "cumque", "suscipit", "repudiandae", "eius" },
                            Country = "Eritrea",
                            CreatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 418, DateTimeKind.Utc).AddTicks(9755),
                            CreatedBy = "",
                            Description = "Libero ut ut aliquam esse deleniti similique sapiente est debitis.",
                            Directors = new List<string> { "blanditiis", "dignissimos", "ratione" },
                            DurationMinutes = 104,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=734",
                            Rating = 9.981618813595647,
                            ReleaseDate = new DateTime(2024, 5, 2, 8, 19, 34, 903, DateTimeKind.Local).AddTicks(2294),
                            State = 4,
                            Title = "Practical Steel Cheese",
                            TrailerUrl = "http://vinnie.com",
                            UpdatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 418, DateTimeKind.Utc).AddTicks(9755)
                        },
                        new
                        {
                            Id = new Guid("4d19eb6a-0171-4f3c-896c-d2683eaf383f"),
                            Cast = new List<string> { "hic", "praesentium", "ad", "quisquam", "magni", "sequi" },
                            Country = "Mozambique",
                            CreatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 418, DateTimeKind.Utc).AddTicks(9852),
                            CreatedBy = "",
                            Description = "Et voluptas vel nihil est commodi dolorum.",
                            Directors = new List<string> { "consequatur" },
                            DurationMinutes = 76,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=945",
                            Rating = 9.9498424073999097,
                            ReleaseDate = new DateTime(2020, 11, 12, 4, 31, 40, 599, DateTimeKind.Local).AddTicks(6208),
                            State = 4,
                            Title = "Refined Concrete Mouse",
                            TrailerUrl = "http://nolan.org",
                            UpdatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 418, DateTimeKind.Utc).AddTicks(9852)
                        },
                        new
                        {
                            Id = new Guid("0bb1f535-07df-4250-b2f2-ada70c7e49ac"),
                            Cast = new List<string> { "in", "repellendus", "quos", "voluptas", "quis" },
                            Country = "Hong Kong",
                            CreatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 418, DateTimeKind.Utc).AddTicks(9939),
                            CreatedBy = "",
                            Description = "Autem quis dolorum non occaecati.",
                            Directors = new List<string> { "voluptatibus", "sequi", "libero" },
                            DurationMinutes = 144,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=1047",
                            Rating = 7.5027849352410589,
                            ReleaseDate = new DateTime(2024, 12, 15, 6, 49, 26, 442, DateTimeKind.Local).AddTicks(8331),
                            State = 4,
                            Title = "Handmade Granite Shoes",
                            TrailerUrl = "http://khalid.info",
                            UpdatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 418, DateTimeKind.Utc).AddTicks(9940)
                        },
                        new
                        {
                            Id = new Guid("20c265a0-294b-4558-a400-7250855fc1c3"),
                            Cast = new List<string> { "nesciunt", "commodi", "sint" },
                            Country = "Myanmar",
                            CreatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 419, DateTimeKind.Utc).AddTicks(55),
                            CreatedBy = "",
                            Description = "Assumenda aspernatur ex vitae non in quo dolor eum harum.",
                            Directors = new List<string> { "assumenda", "sit" },
                            DurationMinutes = 178,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=725",
                            Rating = 1.8561467869351831,
                            ReleaseDate = new DateTime(2020, 10, 31, 10, 7, 5, 810, DateTimeKind.Local),
                            State = 4,
                            Title = "Generic Concrete Pizza",
                            TrailerUrl = "https://wendell.info",
                            UpdatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 419, DateTimeKind.Utc).AddTicks(56)
                        },
                        new
                        {
                            Id = new Guid("78364df5-1784-460d-8ca3-6ba27dd892cc"),
                            Cast = new List<string> { "optio", "blanditiis", "distinctio" },
                            Country = "Switzerland",
                            CreatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 419, DateTimeKind.Utc).AddTicks(145),
                            CreatedBy = "",
                            Description = "Voluptatibus odit veritatis voluptatem quia optio et possimus.",
                            Directors = new List<string> { "dolorem" },
                            DurationMinutes = 158,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=830",
                            Rating = 1.6764278201476355,
                            ReleaseDate = new DateTime(2024, 8, 26, 12, 26, 22, 938, DateTimeKind.Local).AddTicks(2667),
                            State = 4,
                            Title = "Unbranded Metal Gloves",
                            TrailerUrl = "https://jakob.com",
                            UpdatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 419, DateTimeKind.Utc).AddTicks(145)
                        },
                        new
                        {
                            Id = new Guid("c045b5a7-b5c3-4685-92c5-cb2cd7e9ac8f"),
                            Cast = new List<string> { "perferendis", "quisquam", "quam", "architecto" },
                            Country = "El Salvador",
                            CreatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 419, DateTimeKind.Utc).AddTicks(260),
                            CreatedBy = "",
                            Description = "Consectetur molestiae pariatur asperiores fugit eos et debitis quia.",
                            Directors = new List<string> { "assumenda", "molestiae", "ipsum" },
                            DurationMinutes = 122,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=844",
                            Rating = 8.2107913516187025,
                            ReleaseDate = new DateTime(2020, 10, 9, 8, 3, 39, 892, DateTimeKind.Local).AddTicks(340),
                            State = 4,
                            Title = "Refined Soft Towels",
                            TrailerUrl = "https://hailee.biz",
                            UpdatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 419, DateTimeKind.Utc).AddTicks(260)
                        },
                        new
                        {
                            Id = new Guid("556632e9-ee9a-4453-b590-1d191d5cdb89"),
                            Cast = new List<string> { "ipsa", "amet", "maiores", "minus", "hic" },
                            Country = "Djibouti",
                            CreatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 419, DateTimeKind.Utc).AddTicks(357),
                            CreatedBy = "",
                            Description = "Est id natus et ipsa soluta.",
                            Directors = new List<string> { "vel" },
                            DurationMinutes = 95,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=992",
                            Rating = 9.5534374516425835,
                            ReleaseDate = new DateTime(2015, 8, 12, 22, 14, 30, 95, DateTimeKind.Local).AddTicks(9873),
                            State = 4,
                            Title = "Gorgeous Wooden Bacon",
                            TrailerUrl = "http://adelia.org",
                            UpdatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 419, DateTimeKind.Utc).AddTicks(358)
                        },
                        new
                        {
                            Id = new Guid("f3be8980-039e-412f-ba39-4a49ed9ba797"),
                            Cast = new List<string> { "quaerat", "incidunt", "est", "vel", "quo" },
                            Country = "Iceland",
                            CreatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 419, DateTimeKind.Utc).AddTicks(455),
                            CreatedBy = "",
                            Description = "Aliquid temporibus et omnis nam totam veritatis.",
                            Directors = new List<string> { "qui", "similique" },
                            DurationMinutes = 107,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=578",
                            Rating = 9.4780139837933195,
                            ReleaseDate = new DateTime(2017, 7, 10, 6, 10, 16, 924, DateTimeKind.Local).AddTicks(284),
                            State = 4,
                            Title = "Generic Steel Sausages",
                            TrailerUrl = "https://emmalee.org",
                            UpdatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 419, DateTimeKind.Utc).AddTicks(455)
                        },
                        new
                        {
                            Id = new Guid("c352b7c2-f9d4-47d3-a9c8-ec615848d926"),
                            Cast = new List<string> { "ut", "sequi", "soluta", "sit", "omnis", "repellendus" },
                            Country = "Cape Verde",
                            CreatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 419, DateTimeKind.Utc).AddTicks(726),
                            CreatedBy = "",
                            Description = "Explicabo sed nihil velit fugit et velit doloremque veritatis reiciendis.",
                            Directors = new List<string> { "corrupti", "accusamus" },
                            DurationMinutes = 115,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=532",
                            Rating = 8.6627206003112427,
                            ReleaseDate = new DateTime(2019, 10, 14, 14, 4, 43, 209, DateTimeKind.Local).AddTicks(5162),
                            State = 4,
                            Title = "Tasty Wooden Sausages",
                            TrailerUrl = "https://maritza.com",
                            UpdatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 419, DateTimeKind.Utc).AddTicks(726)
                        },
                        new
                        {
                            Id = new Guid("4e731ab8-647e-4481-9cc9-2c7d035099ee"),
                            Cast = new List<string> { "autem", "rerum", "fugit" },
                            Country = "French Polynesia",
                            CreatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 419, DateTimeKind.Utc).AddTicks(828),
                            CreatedBy = "",
                            Description = "Non ullam et.",
                            Directors = new List<string> { "distinctio", "nisi", "minus" },
                            DurationMinutes = 140,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=1056",
                            Rating = 5.1058691742420512,
                            ReleaseDate = new DateTime(2016, 9, 7, 2, 43, 18, 932, DateTimeKind.Local).AddTicks(8313),
                            State = 4,
                            Title = "Fantastic Concrete Car",
                            TrailerUrl = "http://barry.biz",
                            UpdatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 419, DateTimeKind.Utc).AddTicks(828)
                        },
                        new
                        {
                            Id = new Guid("93776869-e749-4976-8efc-1d774f4bc2ce"),
                            Cast = new List<string> { "adipisci", "nihil", "expedita", "voluptas", "et", "facilis", "autem" },
                            Country = "Aruba",
                            CreatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 419, DateTimeKind.Utc).AddTicks(903),
                            CreatedBy = "",
                            Description = "Ut rerum nesciunt dolorum laboriosam ipsa dolorem odit facere omnis.",
                            Directors = new List<string> { "ipsa" },
                            DurationMinutes = 177,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=983",
                            Rating = 7.3607124705775311,
                            ReleaseDate = new DateTime(2024, 12, 9, 5, 46, 53, 156, DateTimeKind.Local).AddTicks(3101),
                            State = 4,
                            Title = "Awesome Wooden Towels",
                            TrailerUrl = "https://cory.net",
                            UpdatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 419, DateTimeKind.Utc).AddTicks(903)
                        },
                        new
                        {
                            Id = new Guid("d8e12eb4-3bc4-404b-9b58-fc8542a8d374"),
                            Cast = new List<string> { "optio", "aperiam", "maxime", "qui", "sint", "voluptas" },
                            Country = "Guatemala",
                            CreatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 419, DateTimeKind.Utc).AddTicks(1029),
                            CreatedBy = "",
                            Description = "Et ea nobis.",
                            Directors = new List<string> { "eligendi", "rem", "consequatur" },
                            DurationMinutes = 115,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=478",
                            Rating = 3.7716814561258385,
                            ReleaseDate = new DateTime(2021, 1, 30, 13, 9, 47, 589, DateTimeKind.Local).AddTicks(4725),
                            State = 4,
                            Title = "Gorgeous Plastic Hat",
                            TrailerUrl = "https://rita.org",
                            UpdatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 419, DateTimeKind.Utc).AddTicks(1030)
                        },
                        new
                        {
                            Id = new Guid("cd752882-f49c-430a-b9c8-f16bd05c2b56"),
                            Cast = new List<string> { "id", "dolorum", "labore", "earum", "quo", "excepturi", "consequatur" },
                            Country = "France",
                            CreatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 419, DateTimeKind.Utc).AddTicks(1110),
                            CreatedBy = "",
                            Description = "Quia iste architecto perferendis voluptatem sit tempora est.",
                            Directors = new List<string> { "consequatur" },
                            DurationMinutes = 118,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=85",
                            Rating = 6.5393721277377468,
                            ReleaseDate = new DateTime(2015, 10, 2, 20, 49, 5, 140, DateTimeKind.Local).AddTicks(703),
                            State = 4,
                            Title = "Small Rubber Gloves",
                            TrailerUrl = "https://charles.org",
                            UpdatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 419, DateTimeKind.Utc).AddTicks(1110)
                        },
                        new
                        {
                            Id = new Guid("727e14bc-547e-4f68-aab4-b3218627bc1d"),
                            Cast = new List<string> { "voluptatum", "ducimus", "iure", "laboriosam", "aliquid" },
                            Country = "Ecuador",
                            CreatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 419, DateTimeKind.Utc).AddTicks(1233),
                            CreatedBy = "",
                            Description = "Cumque quibusdam assumenda illo.",
                            Directors = new List<string> { "est", "tempore" },
                            DurationMinutes = 132,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=554",
                            Rating = 1.0947815715586238,
                            ReleaseDate = new DateTime(2024, 1, 26, 8, 26, 4, 479, DateTimeKind.Local).AddTicks(3650),
                            State = 4,
                            Title = "Ergonomic Soft Pizza",
                            TrailerUrl = "https://hyman.name",
                            UpdatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 419, DateTimeKind.Utc).AddTicks(1233)
                        },
                        new
                        {
                            Id = new Guid("c8cb224d-aba0-4d45-950b-d20a24efe2c6"),
                            Cast = new List<string> { "sed", "qui", "perspiciatis", "eos", "cum", "iure" },
                            Country = "Canada",
                            CreatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 419, DateTimeKind.Utc).AddTicks(1311),
                            CreatedBy = "",
                            Description = "Modi laborum modi ex nihil officiis sit id nam.",
                            Directors = new List<string> { "non" },
                            DurationMinutes = 76,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=790",
                            Rating = 3.030982345732653,
                            ReleaseDate = new DateTime(2022, 8, 17, 20, 29, 44, 149, DateTimeKind.Local).AddTicks(4997),
                            State = 4,
                            Title = "Generic Granite Car",
                            TrailerUrl = "https://cara.org",
                            UpdatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 419, DateTimeKind.Utc).AddTicks(1311)
                        },
                        new
                        {
                            Id = new Guid("adeac3a9-a870-4d80-8eeb-37c12356c7d3"),
                            Cast = new List<string> { "tempora", "cupiditate", "laborum", "temporibus", "eligendi" },
                            Country = "Antigua and Barbuda",
                            CreatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 419, DateTimeKind.Utc).AddTicks(1403),
                            CreatedBy = "",
                            Description = "Maxime omnis quaerat quia quis doloribus voluptatem.",
                            Directors = new List<string> { "maiores" },
                            DurationMinutes = 164,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=93",
                            Rating = 9.7157165886376973,
                            ReleaseDate = new DateTime(2023, 4, 22, 18, 0, 21, 412, DateTimeKind.Local).AddTicks(2784),
                            State = 4,
                            Title = "Licensed Granite Mouse",
                            TrailerUrl = "http://idella.org",
                            UpdatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 419, DateTimeKind.Utc).AddTicks(1403)
                        },
                        new
                        {
                            Id = new Guid("5d786f1d-d5f5-4166-bafc-6a5729e3f45e"),
                            Cast = new List<string> { "labore", "esse", "dolor" },
                            Country = "Jordan",
                            CreatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 419, DateTimeKind.Utc).AddTicks(1509),
                            CreatedBy = "",
                            Description = "Delectus cupiditate quis sit fugiat sequi sunt.",
                            Directors = new List<string> { "ipsa", "voluptates", "qui" },
                            DurationMinutes = 156,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=515",
                            Rating = 4.8910199979032543,
                            ReleaseDate = new DateTime(2019, 5, 20, 23, 9, 32, 548, DateTimeKind.Local).AddTicks(6310),
                            State = 4,
                            Title = "Generic Soft Table",
                            TrailerUrl = "https://alessandra.info",
                            UpdatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 419, DateTimeKind.Utc).AddTicks(1509)
                        },
                        new
                        {
                            Id = new Guid("b02dd64b-2ecd-40f3-93d4-20b0bc7605c5"),
                            Cast = new List<string> { "placeat", "dolores", "aut", "laudantium", "ullam", "et", "consequatur" },
                            Country = "Democratic People's Republic of Korea",
                            CreatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 419, DateTimeKind.Utc).AddTicks(1591),
                            CreatedBy = "",
                            Description = "Voluptatem voluptas deserunt dolorum repudiandae doloribus.",
                            Directors = new List<string> { "quae", "natus", "voluptatibus" },
                            DurationMinutes = 169,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=502",
                            Rating = 1.1383336447629535,
                            ReleaseDate = new DateTime(2023, 11, 20, 3, 36, 53, 490, DateTimeKind.Local).AddTicks(9347),
                            State = 4,
                            Title = "Refined Steel Keyboard",
                            TrailerUrl = "https://roscoe.info",
                            UpdatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 419, DateTimeKind.Utc).AddTicks(1592)
                        },
                        new
                        {
                            Id = new Guid("3425be72-4d5b-4274-83ea-adbae7a7e6f3"),
                            Cast = new List<string> { "tempore", "sunt", "enim" },
                            Country = "Anguilla",
                            CreatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 419, DateTimeKind.Utc).AddTicks(1746),
                            CreatedBy = "",
                            Description = "Et ea eaque sint.",
                            Directors = new List<string> { "et", "debitis", "est" },
                            DurationMinutes = 106,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=379",
                            Rating = 4.1243773592159769,
                            ReleaseDate = new DateTime(2023, 12, 24, 16, 36, 36, 903, DateTimeKind.Local).AddTicks(6639),
                            State = 4,
                            Title = "Incredible Cotton Sausages",
                            TrailerUrl = "http://polly.net",
                            UpdatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 419, DateTimeKind.Utc).AddTicks(1746)
                        },
                        new
                        {
                            Id = new Guid("41e263f5-0464-4afd-adaf-58314356477e"),
                            Cast = new List<string> { "natus", "cumque", "voluptatibus", "velit", "voluptatem", "hic" },
                            Country = "Spain",
                            CreatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 419, DateTimeKind.Utc).AddTicks(1824),
                            CreatedBy = "",
                            Description = "Qui beatae labore veniam itaque blanditiis officiis.",
                            Directors = new List<string> { "deserunt", "doloremque" },
                            DurationMinutes = 144,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=251",
                            Rating = 3.7378945237483796,
                            ReleaseDate = new DateTime(2018, 4, 11, 5, 51, 11, 858, DateTimeKind.Local).AddTicks(2828),
                            State = 4,
                            Title = "Unbranded Cotton Salad",
                            TrailerUrl = "https://elody.biz",
                            UpdatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 419, DateTimeKind.Utc).AddTicks(1824)
                        },
                        new
                        {
                            Id = new Guid("c007e441-2803-49a8-8ccc-e452fad1525f"),
                            Cast = new List<string> { "quisquam", "voluptates", "aliquam", "sequi", "eos", "quo" },
                            Country = "Mali",
                            CreatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 419, DateTimeKind.Utc).AddTicks(1910),
                            CreatedBy = "",
                            Description = "Quis nihil fuga facilis labore.",
                            Directors = new List<string> { "ipsum", "laborum" },
                            DurationMinutes = 117,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=803",
                            Rating = 8.5576942044900086,
                            ReleaseDate = new DateTime(2020, 8, 25, 7, 18, 17, 285, DateTimeKind.Local).AddTicks(6540),
                            State = 4,
                            Title = "Intelligent Metal Chicken",
                            TrailerUrl = "https://beau.name",
                            UpdatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 419, DateTimeKind.Utc).AddTicks(1910)
                        },
                        new
                        {
                            Id = new Guid("9233c6b9-e60e-4d04-b269-a5981cf91e94"),
                            Cast = new List<string> { "dolorem", "quos", "ipsam" },
                            Country = "Tanzania",
                            CreatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 419, DateTimeKind.Utc).AddTicks(2032),
                            CreatedBy = "",
                            Description = "Totam nostrum veniam.",
                            Directors = new List<string> { "et", "porro" },
                            DurationMinutes = 120,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=605",
                            Rating = 4.3519597856093215,
                            ReleaseDate = new DateTime(2020, 7, 10, 8, 57, 0, 821, DateTimeKind.Local).AddTicks(282),
                            State = 4,
                            Title = "Gorgeous Frozen Bacon",
                            TrailerUrl = "https://xzavier.org",
                            UpdatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 419, DateTimeKind.Utc).AddTicks(2032)
                        },
                        new
                        {
                            Id = new Guid("d61b6dd0-43b0-47a2-a21b-31b9af4e6c06"),
                            Cast = new List<string> { "beatae", "molestias", "molestias" },
                            Country = "Micronesia",
                            CreatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 419, DateTimeKind.Utc).AddTicks(2110),
                            CreatedBy = "",
                            Description = "Voluptatibus cumque veritatis debitis.",
                            Directors = new List<string> { "et" },
                            DurationMinutes = 179,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=482",
                            Rating = 4.6791240924529545,
                            ReleaseDate = new DateTime(2021, 7, 16, 2, 1, 58, 206, DateTimeKind.Local).AddTicks(5045),
                            State = 4,
                            Title = "Refined Plastic Sausages",
                            TrailerUrl = "https://candelario.net",
                            UpdatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 419, DateTimeKind.Utc).AddTicks(2110)
                        },
                        new
                        {
                            Id = new Guid("0a174afe-1607-4bdc-8805-4a7a14dd197d"),
                            Cast = new List<string> { "occaecati", "qui", "quis", "ut", "iste", "veniam" },
                            Country = "Ukraine",
                            CreatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 419, DateTimeKind.Utc).AddTicks(2182),
                            CreatedBy = "",
                            Description = "Deleniti possimus iusto fugiat.",
                            Directors = new List<string> { "ab", "at", "fuga" },
                            DurationMinutes = 82,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=307",
                            Rating = 7.200460479478398,
                            ReleaseDate = new DateTime(2024, 7, 31, 23, 28, 29, 903, DateTimeKind.Local).AddTicks(1760),
                            State = 4,
                            Title = "Generic Steel Chips",
                            TrailerUrl = "https://titus.name",
                            UpdatedAt = new DateTime(2025, 4, 23, 6, 11, 56, 419, DateTimeKind.Utc).AddTicks(2182)
                        });
                });

            modelBuilder.Entity("Firebase_Auth.Data.Entities.Authentication.RolePermission", b =>
                {
                    b.HasOne("Firebase_Auth.Data.Entities.Authentication.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Firebase_Auth.Data.Entities.Authentication.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Firebase_Auth.Data.Entities.Authentication.User", b =>
                {
                    b.HasOne("Firebase_Auth.Data.Entities.Authentication.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Firebase_Auth.Data.Entities.Authentication.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Firebase_Auth.Data.Entities.Authentication.Role", b =>
                {
                    b.Navigation("RolePermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
