// <auto-generated />
using System;
using System.Collections.Generic;
using Firebase_Auth.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace firebase_auth.Migrations
{
    [DbContext(typeof(CoreDbContext))]
    [Migration("20250502034838_NotificationEntity")]
    partial class NotificationEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Firebase_Auth.Data.Entities.Authentication.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Code = "CreateContent",
                            Description = "Permission to create content",
                            Name = "CreateContent",
                            State = 4
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Code = "EditContent",
                            Description = "Permission to edit content",
                            Name = "EditContent",
                            State = 4
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Code = "DeleteContent",
                            Description = "Permission to delete content",
                            Name = "DeleteContent",
                            State = 4
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Code = "ViewContent",
                            Description = "Permission to view content",
                            Name = "ViewContent",
                            State = 4
                        });
                });

            modelBuilder.Entity("Firebase_Auth.Data.Entities.Authentication.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Administrator role with full permissions",
                            Name = "admin",
                            State = 4
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Description = "Editor role with editing permissions",
                            Name = "moderator",
                            State = 4
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Description = "User role with viewing permissions",
                            Name = "user",
                            State = 4
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            Description = "Root",
                            Name = "root",
                            State = 4
                        });
                });

            modelBuilder.Entity("Firebase_Auth.Data.Entities.Authentication.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("99999999-9999-9999-9999-999999999999"),
                            PermissionId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            RoleId = new Guid("99999999-9999-9999-9999-999999999999"),
                            PermissionId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            RoleId = new Guid("99999999-9999-9999-9999-999999999999"),
                            PermissionId = new Guid("66666666-6666-6666-6666-666666666666")
                        },
                        new
                        {
                            RoleId = new Guid("99999999-9999-9999-9999-999999999999"),
                            PermissionId = new Guid("77777777-7777-7777-7777-777777777777")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("66666666-6666-6666-6666-666666666666")
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("77777777-7777-7777-7777-777777777777")
                        },
                        new
                        {
                            RoleId = new Guid("22222222-2222-2222-2222-222222222222"),
                            PermissionId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            RoleId = new Guid("22222222-2222-2222-2222-222222222222"),
                            PermissionId = new Guid("77777777-7777-7777-7777-777777777777")
                        },
                        new
                        {
                            RoleId = new Guid("33333333-3333-3333-3333-333333333333"),
                            PermissionId = new Guid("77777777-7777-7777-7777-777777777777")
                        });
                });

            modelBuilder.Entity("Firebase_Auth.Data.Entities.Authentication.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdditionalData")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeviceToken")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FirebaseUid")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("FullName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<bool>("RequirePasswordReset")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("FirebaseUid")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Firebase_Auth.Data.Entities.Common.Notification.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Destination")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NotificationRecipient")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PushOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Firebase_Auth.Data.Entities.Movies.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<string>>("Cast")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Directors")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Language")
                        .HasColumnType("text");

                    b.Property<string>("PosterUrl")
                        .HasColumnType("text");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TrailerUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9f204ffd-cde9-4fcb-abd3-5f0abc746d62"),
                            Cast = new List<string> { "deleniti", "quia", "id", "totam", "qui", "maxime" },
                            Country = "New Caledonia",
                            CreatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 803, DateTimeKind.Utc).AddTicks(8254),
                            CreatedBy = "",
                            Description = "Temporibus quos ipsa est minima ea reprehenderit enim qui.",
                            Directors = new List<string> { "ducimus", "fugit" },
                            DurationMinutes = 109,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=475",
                            Rating = 4.0259013343481529,
                            ReleaseDate = new DateTime(2017, 2, 28, 16, 24, 4, 564, DateTimeKind.Local).AddTicks(1496),
                            State = 4,
                            Title = "Unbranded Frozen Ball",
                            TrailerUrl = "https://lela.com",
                            UpdatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 803, DateTimeKind.Utc).AddTicks(8266)
                        },
                        new
                        {
                            Id = new Guid("464cc915-c533-4ae6-a4ea-16def9444471"),
                            Cast = new List<string> { "itaque", "est", "aliquid" },
                            Country = "Guinea",
                            CreatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(4829),
                            CreatedBy = "",
                            Description = "Veniam ab quidem praesentium harum consequatur.",
                            Directors = new List<string> { "rerum", "amet" },
                            DurationMinutes = 89,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=454",
                            Rating = 5.0226247168541942,
                            ReleaseDate = new DateTime(2018, 9, 14, 15, 9, 37, 764, DateTimeKind.Local).AddTicks(3038),
                            State = 4,
                            Title = "Licensed Frozen Hat",
                            TrailerUrl = "https://cordia.biz",
                            UpdatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(4831)
                        },
                        new
                        {
                            Id = new Guid("c4158d64-4732-480e-b221-6ec5a747d767"),
                            Cast = new List<string> { "qui", "at", "laborum", "ipsam", "magnam" },
                            Country = "Solomon Islands",
                            CreatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(5703),
                            CreatedBy = "",
                            Description = "Sapiente corrupti iusto et.",
                            Directors = new List<string> { "dolores" },
                            DurationMinutes = 77,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=526",
                            Rating = 8.9723436409248318,
                            ReleaseDate = new DateTime(2021, 2, 26, 20, 0, 52, 665, DateTimeKind.Local).AddTicks(1867),
                            State = 4,
                            Title = "Handcrafted Plastic Sausages",
                            TrailerUrl = "https://montana.info",
                            UpdatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(5703)
                        },
                        new
                        {
                            Id = new Guid("5c63ef18-b0db-4782-bee7-c1fa3a4a188d"),
                            Cast = new List<string> { "eaque", "dolorum", "est" },
                            Country = "Paraguay",
                            CreatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(5892),
                            CreatedBy = "",
                            Description = "Debitis eum minima qui nostrum facere quis molestiae unde.",
                            Directors = new List<string> { "molestias", "repellendus", "quia" },
                            DurationMinutes = 158,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=882",
                            Rating = 2.5535430929659531,
                            ReleaseDate = new DateTime(2016, 6, 24, 23, 16, 1, 462, DateTimeKind.Local).AddTicks(6939),
                            State = 4,
                            Title = "Small Plastic Shoes",
                            TrailerUrl = "http://leta.biz",
                            UpdatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(5892)
                        },
                        new
                        {
                            Id = new Guid("fcf5ee3d-2462-498c-9b73-ce0062493d1e"),
                            Cast = new List<string> { "sed", "qui", "deleniti", "quasi", "esse", "reiciendis", "qui" },
                            Country = "Cambodia",
                            CreatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(6006),
                            CreatedBy = "",
                            Description = "Ut incidunt sint dolor atque corrupti mollitia temporibus alias et.",
                            Directors = new List<string> { "tempore", "id" },
                            DurationMinutes = 90,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=22",
                            Rating = 4.1301973972157544,
                            ReleaseDate = new DateTime(2022, 5, 24, 14, 46, 29, 963, DateTimeKind.Local).AddTicks(9944),
                            State = 4,
                            Title = "Handcrafted Granite Mouse",
                            TrailerUrl = "http://myrtie.info",
                            UpdatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(6007)
                        },
                        new
                        {
                            Id = new Guid("ba16faec-ba78-4935-a1e0-e617bd0ad80d"),
                            Cast = new List<string> { "fugiat", "hic", "quo", "laudantium", "voluptates", "tempora" },
                            Country = "Uganda",
                            CreatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(6149),
                            CreatedBy = "",
                            Description = "Occaecati voluptatum dolorum et aspernatur fugit ut eaque.",
                            Directors = new List<string> { "corrupti" },
                            DurationMinutes = 93,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=957",
                            Rating = 2.0887965497834182,
                            ReleaseDate = new DateTime(2021, 2, 7, 19, 47, 1, 434, DateTimeKind.Local).AddTicks(1959),
                            State = 4,
                            Title = "Refined Metal Tuna",
                            TrailerUrl = "http://viviane.net",
                            UpdatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(6150)
                        },
                        new
                        {
                            Id = new Guid("6ef61c00-2d30-4656-826f-9480376ecdd2"),
                            Cast = new List<string> { "alias", "voluptates", "ipsum", "accusamus", "mollitia" },
                            Country = "Algeria",
                            CreatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(6255),
                            CreatedBy = "",
                            Description = "Asperiores id voluptatem atque quia et.",
                            Directors = new List<string> { "sed", "eligendi", "molestiae" },
                            DurationMinutes = 111,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=170",
                            Rating = 7.0177515711358147,
                            ReleaseDate = new DateTime(2020, 6, 6, 3, 23, 37, 701, DateTimeKind.Local).AddTicks(7022),
                            State = 4,
                            Title = "Fantastic Metal Fish",
                            TrailerUrl = "https://shanna.biz",
                            UpdatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(6255)
                        },
                        new
                        {
                            Id = new Guid("3b0bee7f-a587-4457-8f5b-49ab6cb8ad1e"),
                            Cast = new List<string> { "necessitatibus", "aut", "doloribus", "qui" },
                            Country = "Christmas Island",
                            CreatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(6351),
                            CreatedBy = "",
                            Description = "Fuga tempore quo voluptatem pariatur nam quia quia soluta.",
                            Directors = new List<string> { "vel", "sed" },
                            DurationMinutes = 73,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=341",
                            Rating = 3.2464523595297012,
                            ReleaseDate = new DateTime(2024, 4, 29, 18, 26, 49, 423, DateTimeKind.Local).AddTicks(5479),
                            State = 4,
                            Title = "Awesome Soft Shoes",
                            TrailerUrl = "http://alexandria.org",
                            UpdatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(6352)
                        },
                        new
                        {
                            Id = new Guid("d4b93cff-1d82-4cf7-895f-fdf85c40905a"),
                            Cast = new List<string> { "deserunt", "alias", "nostrum" },
                            Country = "Singapore",
                            CreatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(6547),
                            CreatedBy = "",
                            Description = "Dolorem magni harum consequatur aspernatur aut mollitia voluptatibus quos.",
                            Directors = new List<string> { "at", "vel", "in" },
                            DurationMinutes = 85,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=946",
                            Rating = 8.577289558709019,
                            ReleaseDate = new DateTime(2023, 11, 6, 5, 58, 26, 537, DateTimeKind.Local).AddTicks(7029),
                            State = 4,
                            Title = "Handmade Metal Cheese",
                            TrailerUrl = "https://chase.name",
                            UpdatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(6548)
                        },
                        new
                        {
                            Id = new Guid("573bc2e5-faac-4cab-89b8-8c582a1d4ca0"),
                            Cast = new List<string> { "similique", "eum", "dolor", "pariatur" },
                            Country = "United Kingdom",
                            CreatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(6649),
                            CreatedBy = "",
                            Description = "Earum sed tempora non.",
                            Directors = new List<string> { "corrupti", "eum", "dolorum" },
                            DurationMinutes = 92,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=101",
                            Rating = 7.3251554406722486,
                            ReleaseDate = new DateTime(2018, 12, 1, 21, 59, 39, 222, DateTimeKind.Local).AddTicks(4152),
                            State = 4,
                            Title = "Gorgeous Frozen Keyboard",
                            TrailerUrl = "http://madelyn.org",
                            UpdatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(6649)
                        },
                        new
                        {
                            Id = new Guid("f62a1b17-809a-4bce-aa53-1c92c21fdef1"),
                            Cast = new List<string> { "modi", "sunt", "dolores", "ut", "ducimus" },
                            Country = "Andorra",
                            CreatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(6761),
                            CreatedBy = "",
                            Description = "Sint deserunt sed et veritatis totam ipsum culpa iusto.",
                            Directors = new List<string> { "illo" },
                            DurationMinutes = 108,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=201",
                            Rating = 4.8060241795842042,
                            ReleaseDate = new DateTime(2024, 5, 5, 21, 4, 26, 809, DateTimeKind.Local).AddTicks(5363),
                            State = 4,
                            Title = "Intelligent Cotton Fish",
                            TrailerUrl = "http://glen.net",
                            UpdatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(6761)
                        },
                        new
                        {
                            Id = new Guid("26c2f9b1-10f9-4418-997f-03f9a8e2493f"),
                            Cast = new List<string> { "dolor", "corrupti", "ratione", "blanditiis", "ut", "nihil", "eaque" },
                            Country = "Guatemala",
                            CreatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(6862),
                            CreatedBy = "",
                            Description = "Voluptas deserunt ut commodi.",
                            Directors = new List<string> { "consequatur" },
                            DurationMinutes = 113,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=503",
                            Rating = 1.5493561982824331,
                            ReleaseDate = new DateTime(2016, 10, 8, 7, 49, 46, 45, DateTimeKind.Local).AddTicks(1556),
                            State = 4,
                            Title = "Intelligent Frozen Pizza",
                            TrailerUrl = "https://ebba.net",
                            UpdatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(6862)
                        },
                        new
                        {
                            Id = new Guid("5a22c082-6db5-4912-a2fd-584020248a64"),
                            Cast = new List<string> { "id", "perspiciatis", "quaerat", "error" },
                            Country = "Uzbekistan",
                            CreatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(6963),
                            CreatedBy = "",
                            Description = "Non modi adipisci facilis.",
                            Directors = new List<string> { "velit", "aut", "dolores" },
                            DurationMinutes = 84,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=292",
                            Rating = 1.7656142320130566,
                            ReleaseDate = new DateTime(2016, 10, 11, 7, 35, 32, 306, DateTimeKind.Local).AddTicks(6215),
                            State = 4,
                            Title = "Incredible Granite Shirt",
                            TrailerUrl = "https://price.name",
                            UpdatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(6963)
                        },
                        new
                        {
                            Id = new Guid("b9df24b2-9601-4026-b4ef-99b574a776f3"),
                            Cast = new List<string> { "animi", "corrupti", "quibusdam" },
                            Country = "French Southern Territories",
                            CreatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(7094),
                            CreatedBy = "",
                            Description = "Porro consectetur quod.",
                            Directors = new List<string> { "voluptas" },
                            DurationMinutes = 132,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=928",
                            Rating = 4.6197424374760159,
                            ReleaseDate = new DateTime(2018, 11, 18, 16, 59, 45, 579, DateTimeKind.Local).AddTicks(9635),
                            State = 4,
                            Title = "Refined Fresh Towels",
                            TrailerUrl = "https://magdalen.name",
                            UpdatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(7094)
                        },
                        new
                        {
                            Id = new Guid("cb13badb-0a01-453d-90cb-a521d50a6127"),
                            Cast = new List<string> { "provident", "unde", "quo", "illum", "architecto" },
                            Country = "Democratic People's Republic of Korea",
                            CreatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(7180),
                            CreatedBy = "",
                            Description = "Enim dolor magni qui suscipit labore sint ullam ullam adipisci.",
                            Directors = new List<string> { "animi" },
                            DurationMinutes = 66,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=229",
                            Rating = 5.2801453035256358,
                            ReleaseDate = new DateTime(2021, 4, 19, 21, 23, 32, 874, DateTimeKind.Local).AddTicks(1892),
                            State = 4,
                            Title = "Fantastic Concrete Towels",
                            TrailerUrl = "http://jaclyn.info",
                            UpdatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(7180)
                        },
                        new
                        {
                            Id = new Guid("7f03098f-4cb7-4591-8352-0169525f8067"),
                            Cast = new List<string> { "possimus", "aliquam", "animi" },
                            Country = "Falkland Islands (Malvinas)",
                            CreatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(7278),
                            CreatedBy = "",
                            Description = "Numquam et et est.",
                            Directors = new List<string> { "voluptatem", "molestiae" },
                            DurationMinutes = 94,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=0",
                            Rating = 6.0942287471189989,
                            ReleaseDate = new DateTime(2022, 6, 30, 10, 59, 4, 760, DateTimeKind.Local).AddTicks(3667),
                            State = 4,
                            Title = "Generic Metal Shoes",
                            TrailerUrl = "https://johann.net",
                            UpdatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(7278)
                        },
                        new
                        {
                            Id = new Guid("125b6486-0537-4acc-bf6a-b4134e5c5d08"),
                            Cast = new List<string> { "qui", "debitis", "dolor", "voluptas" },
                            Country = "Pakistan",
                            CreatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(7386),
                            CreatedBy = "",
                            Description = "Ut eum nam porro est sapiente eum similique enim et.",
                            Directors = new List<string> { "qui" },
                            DurationMinutes = 133,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=961",
                            Rating = 1.0798854997108165,
                            ReleaseDate = new DateTime(2016, 9, 27, 13, 59, 5, 906, DateTimeKind.Local).AddTicks(6032),
                            State = 4,
                            Title = "Sleek Cotton Keyboard",
                            TrailerUrl = "https://lillie.biz",
                            UpdatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(7386)
                        },
                        new
                        {
                            Id = new Guid("49e38583-9a70-4d76-8d31-f67138481aba"),
                            Cast = new List<string> { "rerum", "consequatur", "ratione", "magni" },
                            Country = "Mongolia",
                            CreatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(7477),
                            CreatedBy = "",
                            Description = "Et quam natus.",
                            Directors = new List<string> { "sunt", "voluptas" },
                            DurationMinutes = 111,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=391",
                            Rating = 3.84980310074189,
                            ReleaseDate = new DateTime(2021, 5, 31, 16, 12, 6, 991, DateTimeKind.Local).AddTicks(3273),
                            State = 4,
                            Title = "Gorgeous Soft Shirt",
                            TrailerUrl = "https://lorenzo.net",
                            UpdatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(7477)
                        },
                        new
                        {
                            Id = new Guid("44eca0fd-7d78-4317-b836-e2384289e34d"),
                            Cast = new List<string> { "rerum", "nulla", "dolorem", "et", "modi" },
                            Country = "Montenegro",
                            CreatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(7578),
                            CreatedBy = "",
                            Description = "Veniam a consequuntur.",
                            Directors = new List<string> { "dolores", "quia", "repellat" },
                            DurationMinutes = 139,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=516",
                            Rating = 6.7373915417467565,
                            ReleaseDate = new DateTime(2015, 8, 17, 3, 12, 47, 853, DateTimeKind.Local).AddTicks(15),
                            State = 4,
                            Title = "Sleek Fresh Fish",
                            TrailerUrl = "http://robbie.name",
                            UpdatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(7579)
                        },
                        new
                        {
                            Id = new Guid("bf143d7a-14c2-4524-be66-cdf1a8a19c1e"),
                            Cast = new List<string> { "quasi", "quos", "quibusdam", "velit", "voluptates" },
                            Country = "Andorra",
                            CreatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(7664),
                            CreatedBy = "",
                            Description = "Enim aperiam qui.",
                            Directors = new List<string> { "perferendis" },
                            DurationMinutes = 161,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=20",
                            Rating = 8.1835250622352511,
                            ReleaseDate = new DateTime(2016, 5, 10, 2, 18, 10, 586, DateTimeKind.Local).AddTicks(5562),
                            State = 4,
                            Title = "Licensed Granite Table",
                            TrailerUrl = "https://osborne.info",
                            UpdatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(7665)
                        },
                        new
                        {
                            Id = new Guid("83ba29bc-041b-4f73-9c22-4743153dc6ac"),
                            Cast = new List<string> { "officia", "dolorum", "qui", "est", "amet", "itaque", "magnam" },
                            Country = "Antarctica (the territory South of 60 deg S)",
                            CreatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(7741),
                            CreatedBy = "",
                            Description = "Magnam hic et cum distinctio ratione repudiandae non.",
                            Directors = new List<string> { "quia" },
                            DurationMinutes = 108,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=621",
                            Rating = 7.8613957128705714,
                            ReleaseDate = new DateTime(2022, 6, 28, 15, 38, 1, 620, DateTimeKind.Local).AddTicks(6623),
                            State = 4,
                            Title = "Intelligent Concrete Pizza",
                            TrailerUrl = "http://blanche.org",
                            UpdatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(7741)
                        },
                        new
                        {
                            Id = new Guid("fca7640a-6671-4edc-aea1-06ca9247d532"),
                            Cast = new List<string> { "sunt", "voluptates", "similique" },
                            Country = "Anguilla",
                            CreatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(7863),
                            CreatedBy = "",
                            Description = "Amet omnis iure qui cumque.",
                            Directors = new List<string> { "itaque", "quis" },
                            DurationMinutes = 155,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=782",
                            Rating = 5.079193210846439,
                            ReleaseDate = new DateTime(2021, 5, 21, 23, 8, 14, 331, DateTimeKind.Local).AddTicks(2117),
                            State = 4,
                            Title = "Handmade Fresh Ball",
                            TrailerUrl = "http://helen.name",
                            UpdatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(7864)
                        },
                        new
                        {
                            Id = new Guid("a2613e6a-8a3a-4064-8c29-2a1ff8c86e36"),
                            Cast = new List<string> { "sed", "fugit", "enim" },
                            Country = "Micronesia",
                            CreatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(7947),
                            CreatedBy = "",
                            Description = "Tempore quaerat cum eum dicta hic nisi voluptate.",
                            Directors = new List<string> { "cum" },
                            DurationMinutes = 86,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=35",
                            Rating = 5.0663091129372111,
                            ReleaseDate = new DateTime(2019, 1, 7, 12, 18, 59, 682, DateTimeKind.Local).AddTicks(8659),
                            State = 4,
                            Title = "Incredible Frozen Pants",
                            TrailerUrl = "http://tomas.net",
                            UpdatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(7947)
                        },
                        new
                        {
                            Id = new Guid("f6fec24d-a176-4aa1-834d-6daaaa85c7f9"),
                            Cast = new List<string> { "fuga", "culpa", "facilis" },
                            Country = "Guernsey",
                            CreatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(8033),
                            CreatedBy = "",
                            Description = "Non nihil veritatis quo laudantium autem architecto quia error.",
                            Directors = new List<string> { "numquam" },
                            DurationMinutes = 174,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=314",
                            Rating = 1.3377818498239855,
                            ReleaseDate = new DateTime(2016, 7, 4, 5, 34, 11, 31, DateTimeKind.Local).AddTicks(6079),
                            State = 4,
                            Title = "Tasty Soft Tuna",
                            TrailerUrl = "http://trinity.net",
                            UpdatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(8033)
                        },
                        new
                        {
                            Id = new Guid("dd308284-3b31-4ae9-8d2f-971ec938a094"),
                            Cast = new List<string> { "alias", "repudiandae", "occaecati", "qui", "sint", "in", "officiis" },
                            Country = "Benin",
                            CreatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(8144),
                            CreatedBy = "",
                            Description = "Rem facilis sed aut odio perspiciatis cum odio cum.",
                            Directors = new List<string> { "autem", "maiores" },
                            DurationMinutes = 177,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=544",
                            Rating = 9.8953484810328085,
                            ReleaseDate = new DateTime(2020, 4, 1, 19, 57, 45, 438, DateTimeKind.Local).AddTicks(8471),
                            State = 4,
                            Title = "Sleek Steel Mouse",
                            TrailerUrl = "https://edna.biz",
                            UpdatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(8145)
                        },
                        new
                        {
                            Id = new Guid("37a2bf35-5298-4d1d-8938-7b397a9d06ce"),
                            Cast = new List<string> { "enim", "aspernatur", "iste", "dolorem", "ipsum", "amet", "non" },
                            Country = "Lesotho",
                            CreatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(8242),
                            CreatedBy = "",
                            Description = "Esse quos eligendi enim odit placeat.",
                            Directors = new List<string> { "eaque", "atque", "voluptatem" },
                            DurationMinutes = 127,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=493",
                            Rating = 9.1797584387596487,
                            ReleaseDate = new DateTime(2021, 5, 7, 8, 49, 45, 509, DateTimeKind.Local).AddTicks(310),
                            State = 4,
                            Title = "Small Concrete Chair",
                            TrailerUrl = "http://reece.name",
                            UpdatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(8242)
                        },
                        new
                        {
                            Id = new Guid("68f682c5-8719-4760-aee6-10f2a09a2402"),
                            Cast = new List<string> { "enim", "molestias", "voluptates", "autem", "tempora", "officiis", "magni" },
                            Country = "Cook Islands",
                            CreatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(8396),
                            CreatedBy = "",
                            Description = "Cupiditate et placeat deleniti doloribus consequuntur.",
                            Directors = new List<string> { "velit", "ipsam", "optio" },
                            DurationMinutes = 92,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=224",
                            Rating = 3.729475278998303,
                            ReleaseDate = new DateTime(2018, 3, 11, 13, 25, 0, 363, DateTimeKind.Local).AddTicks(8730),
                            State = 4,
                            Title = "Licensed Granite Bike",
                            TrailerUrl = "http://alfonzo.biz",
                            UpdatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(8397)
                        },
                        new
                        {
                            Id = new Guid("98fca398-344c-4d16-b88d-ef0ac286edcb"),
                            Cast = new List<string> { "minima", "vel", "architecto" },
                            Country = "Botswana",
                            CreatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(8491),
                            CreatedBy = "",
                            Description = "Enim laboriosam nostrum omnis error fugiat quaerat nobis hic.",
                            Directors = new List<string> { "officia", "repudiandae" },
                            DurationMinutes = 131,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=440",
                            Rating = 1.2502412306351585,
                            ReleaseDate = new DateTime(2016, 8, 17, 21, 28, 19, 240, DateTimeKind.Local).AddTicks(152),
                            State = 4,
                            Title = "Sleek Wooden Mouse",
                            TrailerUrl = "http://margarete.biz",
                            UpdatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(8491)
                        },
                        new
                        {
                            Id = new Guid("b3aa2eee-2c67-43b9-8e04-c3befcdce624"),
                            Cast = new List<string> { "eum", "voluptas", "quia", "numquam" },
                            Country = "Kenya",
                            CreatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(8579),
                            CreatedBy = "",
                            Description = "Saepe aliquam ut repellat debitis provident.",
                            Directors = new List<string> { "possimus" },
                            DurationMinutes = 76,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=46",
                            Rating = 6.1714186660905046,
                            ReleaseDate = new DateTime(2020, 5, 28, 21, 34, 3, 888, DateTimeKind.Local).AddTicks(5563),
                            State = 4,
                            Title = "Awesome Rubber Cheese",
                            TrailerUrl = "https://thea.biz",
                            UpdatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(8579)
                        },
                        new
                        {
                            Id = new Guid("0845e447-bf7d-4432-b131-9549b42ebd74"),
                            Cast = new List<string> { "ipsum", "tempore", "assumenda", "ipsa", "autem", "dolore" },
                            Country = "Mozambique",
                            CreatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(8696),
                            CreatedBy = "",
                            Description = "Est aliquid beatae non iure.",
                            Directors = new List<string> { "reiciendis", "esse", "dignissimos" },
                            DurationMinutes = 121,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=1074",
                            Rating = 3.0661580697672068,
                            ReleaseDate = new DateTime(2016, 2, 29, 16, 41, 0, 681, DateTimeKind.Local).AddTicks(1249),
                            State = 4,
                            Title = "Licensed Rubber Gloves",
                            TrailerUrl = "http://jay.info",
                            UpdatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(8696)
                        },
                        new
                        {
                            Id = new Guid("1e0de292-ed2f-48d3-89e3-b630b81ebbdb"),
                            Cast = new List<string> { "nihil", "amet", "doloribus", "perspiciatis", "qui", "in", "est" },
                            Country = "Sierra Leone",
                            CreatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(8787),
                            CreatedBy = "",
                            Description = "Sit libero sequi aliquam in iste qui.",
                            Directors = new List<string> { "sed", "corrupti", "modi" },
                            DurationMinutes = 82,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=1052",
                            Rating = 7.4525035536766522,
                            ReleaseDate = new DateTime(2024, 6, 5, 5, 42, 45, 316, DateTimeKind.Local).AddTicks(6276),
                            State = 4,
                            Title = "Small Rubber Soap",
                            TrailerUrl = "http://zula.biz",
                            UpdatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(8787)
                        },
                        new
                        {
                            Id = new Guid("33905458-dd94-4a73-9463-39e6f3ff786d"),
                            Cast = new List<string> { "ea", "dolorem", "id", "natus" },
                            Country = "Sweden",
                            CreatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(8881),
                            CreatedBy = "",
                            Description = "Rerum numquam mollitia et aut nisi sit magni quae aut.",
                            Directors = new List<string> { "neque" },
                            DurationMinutes = 106,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=186",
                            Rating = 9.6783511568465261,
                            ReleaseDate = new DateTime(2024, 11, 21, 21, 7, 40, 789, DateTimeKind.Local).AddTicks(8807),
                            State = 4,
                            Title = "Incredible Soft Ball",
                            TrailerUrl = "http://nina.name",
                            UpdatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(8881)
                        },
                        new
                        {
                            Id = new Guid("0afe5f1d-2514-43f6-b1c5-ffb428cffe8c"),
                            Cast = new List<string> { "perferendis", "rerum", "sit", "consequatur", "veritatis", "vero", "ut" },
                            Country = "Nauru",
                            CreatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(8999),
                            CreatedBy = "",
                            Description = "Quibusdam optio consequuntur id eos cumque.",
                            Directors = new List<string> { "eos", "debitis" },
                            DurationMinutes = 177,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=658",
                            Rating = 9.2214461834483785,
                            ReleaseDate = new DateTime(2019, 11, 17, 4, 43, 31, 108, DateTimeKind.Local).AddTicks(3449),
                            State = 4,
                            Title = "Practical Granite Shoes",
                            TrailerUrl = "https://elsie.name",
                            UpdatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(9000)
                        },
                        new
                        {
                            Id = new Guid("f99c215e-2128-4092-a870-833ba39b6dfb"),
                            Cast = new List<string> { "est", "laboriosam", "quos", "autem", "quod", "corrupti" },
                            Country = "Uzbekistan",
                            CreatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(9090),
                            CreatedBy = "",
                            Description = "Dignissimos hic soluta fugiat ab.",
                            Directors = new List<string> { "dolor", "est" },
                            DurationMinutes = 150,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=470",
                            Rating = 3.0014457190792556,
                            ReleaseDate = new DateTime(2019, 11, 14, 7, 18, 6, 213, DateTimeKind.Local).AddTicks(3579),
                            State = 4,
                            Title = "Handmade Rubber Chips",
                            TrailerUrl = "https://ernie.net",
                            UpdatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(9091)
                        },
                        new
                        {
                            Id = new Guid("5ce3879e-dbb9-49cf-8e33-a81755c26f24"),
                            Cast = new List<string> { "vero", "in", "non", "reiciendis", "illum", "consectetur" },
                            Country = "Tanzania",
                            CreatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(9351),
                            CreatedBy = "",
                            Description = "Recusandae dicta et voluptatum eveniet iste beatae ea sint a.",
                            Directors = new List<string> { "voluptas", "praesentium", "aspernatur" },
                            DurationMinutes = 146,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=911",
                            Rating = 2.7073020967769681,
                            ReleaseDate = new DateTime(2022, 8, 25, 10, 32, 42, 610, DateTimeKind.Local).AddTicks(1152),
                            State = 4,
                            Title = "Intelligent Granite Bacon",
                            TrailerUrl = "http://blaise.net",
                            UpdatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(9352)
                        },
                        new
                        {
                            Id = new Guid("0cebf456-ca74-48cc-b78f-d9a3122901a0"),
                            Cast = new List<string> { "et", "rerum", "rem" },
                            Country = "Luxembourg",
                            CreatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(9458),
                            CreatedBy = "",
                            Description = "Exercitationem quia animi iure commodi mollitia.",
                            Directors = new List<string> { "odio", "provident", "incidunt" },
                            DurationMinutes = 163,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=490",
                            Rating = 2.3716502145375817,
                            ReleaseDate = new DateTime(2018, 1, 2, 20, 53, 8, 665, DateTimeKind.Local).AddTicks(4943),
                            State = 4,
                            Title = "Sleek Plastic Cheese",
                            TrailerUrl = "http://celia.net",
                            UpdatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(9458)
                        },
                        new
                        {
                            Id = new Guid("dc8be919-53f5-42e6-861d-0f117004b6c4"),
                            Cast = new List<string> { "amet", "architecto", "aut", "dignissimos", "sed", "voluptates" },
                            Country = "Brazil",
                            CreatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(9540),
                            CreatedBy = "",
                            Description = "Molestiae perspiciatis et et vel odit.",
                            Directors = new List<string> { "aliquam" },
                            DurationMinutes = 134,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=1002",
                            Rating = 4.6029024215316232,
                            ReleaseDate = new DateTime(2017, 1, 3, 20, 25, 24, 258, DateTimeKind.Local).AddTicks(5141),
                            State = 4,
                            Title = "Rustic Frozen Table",
                            TrailerUrl = "https://ricardo.info",
                            UpdatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(9540)
                        },
                        new
                        {
                            Id = new Guid("bd08531a-19aa-4c1e-b0dd-18722be4375d"),
                            Cast = new List<string> { "saepe", "reiciendis", "delectus", "laudantium", "magnam" },
                            Country = "Tanzania",
                            CreatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(9652),
                            CreatedBy = "",
                            Description = "Perferendis perferendis voluptas.",
                            Directors = new List<string> { "laboriosam" },
                            DurationMinutes = 87,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=378",
                            Rating = 6.0433346356410365,
                            ReleaseDate = new DateTime(2024, 1, 30, 15, 2, 20, 253, DateTimeKind.Local).AddTicks(8),
                            State = 4,
                            Title = "Handmade Concrete Towels",
                            TrailerUrl = "http://rey.info",
                            UpdatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(9652)
                        },
                        new
                        {
                            Id = new Guid("b1e90098-501e-4217-a6c4-01071274b262"),
                            Cast = new List<string> { "maiores", "soluta", "non" },
                            Country = "Tokelau",
                            CreatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(9726),
                            CreatedBy = "",
                            Description = "Et nulla ex exercitationem dolores quaerat illum aut.",
                            Directors = new List<string> { "nulla", "voluptas" },
                            DurationMinutes = 93,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=574",
                            Rating = 1.2037655046308031,
                            ReleaseDate = new DateTime(2018, 4, 16, 7, 14, 2, 228, DateTimeKind.Local).AddTicks(9856),
                            State = 4,
                            Title = "Licensed Wooden Keyboard",
                            TrailerUrl = "http://micah.biz",
                            UpdatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(9727)
                        },
                        new
                        {
                            Id = new Guid("a67dca8a-f5fa-4fce-9aa5-3264cdbdeb11"),
                            Cast = new List<string> { "alias", "et", "cupiditate", "qui", "rem", "odio", "velit" },
                            Country = "Niue",
                            CreatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(9837),
                            CreatedBy = "",
                            Description = "Sit minus doloremque nobis error rerum.",
                            Directors = new List<string> { "quia", "aut" },
                            DurationMinutes = 144,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=444",
                            Rating = 4.6967551949169453,
                            ReleaseDate = new DateTime(2022, 9, 13, 20, 25, 15, 737, DateTimeKind.Local).AddTicks(8521),
                            State = 4,
                            Title = "Sleek Wooden Gloves",
                            TrailerUrl = "https://neoma.com",
                            UpdatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(9838)
                        },
                        new
                        {
                            Id = new Guid("ffaaaede-f180-41b6-8b15-08eba05291c7"),
                            Cast = new List<string> { "molestias", "itaque", "doloribus", "magnam", "quos", "quis", "repudiandae" },
                            Country = "Malawi",
                            CreatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(9929),
                            CreatedBy = "",
                            Description = "Quos et autem.",
                            Directors = new List<string> { "dolorem", "quo", "mollitia" },
                            DurationMinutes = 112,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=598",
                            Rating = 6.9602803479363118,
                            ReleaseDate = new DateTime(2017, 2, 18, 13, 19, 24, 122, DateTimeKind.Local).AddTicks(4248),
                            State = 4,
                            Title = "Practical Cotton Gloves",
                            TrailerUrl = "https://korbin.com",
                            UpdatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 812, DateTimeKind.Utc).AddTicks(9929)
                        },
                        new
                        {
                            Id = new Guid("5fd41623-3dbd-4fc0-a92e-2e0b00409185"),
                            Cast = new List<string> { "quibusdam", "illum", "fuga", "sunt", "aut" },
                            Country = "Serbia",
                            CreatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 813, DateTimeKind.Utc).AddTicks(14),
                            CreatedBy = "",
                            Description = "Sit quo nemo.",
                            Directors = new List<string> { "doloremque", "eligendi" },
                            DurationMinutes = 103,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=339",
                            Rating = 8.2733550227608497,
                            ReleaseDate = new DateTime(2018, 2, 6, 23, 13, 39, 0, DateTimeKind.Local).AddTicks(3797),
                            State = 4,
                            Title = "Tasty Fresh Chair",
                            TrailerUrl = "https://manuel.info",
                            UpdatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 813, DateTimeKind.Utc).AddTicks(14)
                        },
                        new
                        {
                            Id = new Guid("837adc87-efdd-43f2-a4ff-8231e78576d0"),
                            Cast = new List<string> { "tempore", "culpa", "vero", "magnam", "maiores", "totam", "dolorum" },
                            Country = "Fiji",
                            CreatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 813, DateTimeKind.Utc).AddTicks(121),
                            CreatedBy = "",
                            Description = "Excepturi veniam ullam.",
                            Directors = new List<string> { "placeat" },
                            DurationMinutes = 148,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=339",
                            Rating = 8.6482396583108141,
                            ReleaseDate = new DateTime(2022, 4, 1, 6, 35, 41, 766, DateTimeKind.Local).AddTicks(7797),
                            State = 4,
                            Title = "Practical Concrete Chips",
                            TrailerUrl = "https://liliana.name",
                            UpdatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 813, DateTimeKind.Utc).AddTicks(121)
                        },
                        new
                        {
                            Id = new Guid("ef43dc4e-9f51-4f90-888b-6c99eae65d50"),
                            Cast = new List<string> { "ut", "atque", "quo", "et", "omnis", "atque" },
                            Country = "Zambia",
                            CreatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 813, DateTimeKind.Utc).AddTicks(198),
                            CreatedBy = "",
                            Description = "Esse occaecati ab.",
                            Directors = new List<string> { "ea" },
                            DurationMinutes = 78,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=91",
                            Rating = 3.1854057195075751,
                            ReleaseDate = new DateTime(2019, 10, 25, 3, 28, 16, 504, DateTimeKind.Local).AddTicks(7576),
                            State = 4,
                            Title = "Rustic Rubber Chicken",
                            TrailerUrl = "http://fernando.org",
                            UpdatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 813, DateTimeKind.Utc).AddTicks(199)
                        },
                        new
                        {
                            Id = new Guid("24bbae35-a220-4bb3-964f-c73730e21dfb"),
                            Cast = new List<string> { "quam", "unde", "animi", "est" },
                            Country = "Jamaica",
                            CreatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 813, DateTimeKind.Utc).AddTicks(278),
                            CreatedBy = "",
                            Description = "Libero ad ipsum nulla.",
                            Directors = new List<string> { "ex", "ipsam" },
                            DurationMinutes = 106,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=565",
                            Rating = 5.2833140618896834,
                            ReleaseDate = new DateTime(2021, 3, 16, 22, 9, 18, 582, DateTimeKind.Local).AddTicks(3717),
                            State = 4,
                            Title = "Incredible Metal Towels",
                            TrailerUrl = "https://domenic.name",
                            UpdatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 813, DateTimeKind.Utc).AddTicks(278)
                        },
                        new
                        {
                            Id = new Guid("1a3b298c-c293-4bf0-bdde-7a2c7176e018"),
                            Cast = new List<string> { "nulla", "nulla", "molestias", "ratione", "ea", "voluptatem", "et" },
                            Country = "Israel",
                            CreatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 813, DateTimeKind.Utc).AddTicks(375),
                            CreatedBy = "",
                            Description = "Nesciunt totam sequi dolorem.",
                            Directors = new List<string> { "quia", "nulla" },
                            DurationMinutes = 62,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=95",
                            Rating = 6.9287225109660904,
                            ReleaseDate = new DateTime(2019, 9, 8, 22, 38, 39, 912, DateTimeKind.Local).AddTicks(6513),
                            State = 4,
                            Title = "Handcrafted Soft Gloves",
                            TrailerUrl = "https://jess.com",
                            UpdatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 813, DateTimeKind.Utc).AddTicks(376)
                        },
                        new
                        {
                            Id = new Guid("312216e6-6ef9-4d1f-918b-acc0abf67262"),
                            Cast = new List<string> { "consequuntur", "sed", "dicta" },
                            Country = "Bhutan",
                            CreatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 813, DateTimeKind.Utc).AddTicks(460),
                            CreatedBy = "",
                            Description = "Quo repudiandae facere quo sit perferendis.",
                            Directors = new List<string> { "ut" },
                            DurationMinutes = 90,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=987",
                            Rating = 6.9690531857884617,
                            ReleaseDate = new DateTime(2017, 9, 10, 1, 3, 51, 383, DateTimeKind.Local).AddTicks(8329),
                            State = 4,
                            Title = "Licensed Plastic Chair",
                            TrailerUrl = "https://moriah.info",
                            UpdatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 813, DateTimeKind.Utc).AddTicks(460)
                        },
                        new
                        {
                            Id = new Guid("01938b99-b22f-494a-8dac-d540f61447ce"),
                            Cast = new List<string> { "qui", "et", "corrupti", "enim", "velit" },
                            Country = "Sierra Leone",
                            CreatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 813, DateTimeKind.Utc).AddTicks(536),
                            CreatedBy = "",
                            Description = "Nisi suscipit omnis quam aut.",
                            Directors = new List<string> { "optio", "harum", "occaecati" },
                            DurationMinutes = 75,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=364",
                            Rating = 4.2539205801491953,
                            ReleaseDate = new DateTime(2021, 9, 8, 17, 25, 3, 999, DateTimeKind.Local).AddTicks(3281),
                            State = 4,
                            Title = "Fantastic Frozen Fish",
                            TrailerUrl = "http://reta.info",
                            UpdatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 813, DateTimeKind.Utc).AddTicks(536)
                        },
                        new
                        {
                            Id = new Guid("b3977492-1271-411f-a2d1-4e37a7e123d3"),
                            Cast = new List<string> { "eum", "autem", "corporis" },
                            Country = "South Africa",
                            CreatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 813, DateTimeKind.Utc).AddTicks(655),
                            CreatedBy = "",
                            Description = "Laboriosam qui voluptatem est repudiandae illum quis voluptatibus mollitia.",
                            Directors = new List<string> { "sed", "in" },
                            DurationMinutes = 67,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=733",
                            Rating = 3.7440274888511254,
                            ReleaseDate = new DateTime(2015, 6, 1, 10, 18, 0, 588, DateTimeKind.Local).AddTicks(6920),
                            State = 4,
                            Title = "Handcrafted Soft Chair",
                            TrailerUrl = "http://lavon.net",
                            UpdatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 813, DateTimeKind.Utc).AddTicks(655)
                        },
                        new
                        {
                            Id = new Guid("c5b2f013-5b10-4c7c-8ad8-1e022b59fe7e"),
                            Cast = new List<string> { "dolor", "et", "sit" },
                            Country = "China",
                            CreatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 813, DateTimeKind.Utc).AddTicks(741),
                            CreatedBy = "",
                            Description = "Libero possimus incidunt consequatur animi similique.",
                            Directors = new List<string> { "consequatur" },
                            DurationMinutes = 160,
                            Language = "en",
                            PosterUrl = "https://picsum.photos/640/480/?image=432",
                            Rating = 6.8065352188921606,
                            ReleaseDate = new DateTime(2023, 8, 12, 14, 15, 12, 830, DateTimeKind.Local).AddTicks(1597),
                            State = 4,
                            Title = "Intelligent Rubber Computer",
                            TrailerUrl = "https://kiana.biz",
                            UpdatedAt = new DateTime(2025, 5, 2, 3, 48, 37, 813, DateTimeKind.Utc).AddTicks(741)
                        });
                });

            modelBuilder.Entity("Firebase_Auth.Data.Entities.Authentication.RolePermission", b =>
                {
                    b.HasOne("Firebase_Auth.Data.Entities.Authentication.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Firebase_Auth.Data.Entities.Authentication.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Firebase_Auth.Data.Entities.Authentication.User", b =>
                {
                    b.HasOne("Firebase_Auth.Data.Entities.Authentication.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Firebase_Auth.Data.Entities.Authentication.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Firebase_Auth.Data.Entities.Authentication.Role", b =>
                {
                    b.Navigation("RolePermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
